Add facts about single-variable degree-2 polynomials
math-comp/math-comp pull request #1002
Opened 2023-04-24 09:11 UTC by proux01

##### Motivation for this change

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] ~added corresponding documentation in the headers~
- [x] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)

##### Compatibility with MathComp 2.0

- [ ] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

2023-04-24 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_canonical x :
this does not need the `rcfType` just `fieldType`?

2023-04-24 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Let p := a *: 'X^2 + b*: 'X + c%:P.
Just a little reaction about the general setting 

I would have either put `size p = 2` and then give the exact form with `p_0` `p_1` `_2` 
or  `'X^2 + b *: X + c%:P` as you are in a rcfType. Why you choose this explict form?

2023-04-24 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Proof. by rewrite (_ : 4 = 2 * 2) -1?mulrA 1?mulrACA ?expr2// -natrM. Qed.
```coq 
by rewrite expr2 mulrACA mulrA -natrM.
```

2023-04-24 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root2 : 0 <= delta -> root p ((- b + sqrt delta) / (2 * a)).
Is there not a theorem that states the usual factorization of `p` when `delta` is positive?

2023-04-24 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Hypothesis agt0 : 0 < a.
what about when `a` is negative, would it be more general to take `p` as `monic`?

2023-04-24 18:16 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root2 : 0 <= delta -> root p ((- b + sqrt delta) / (2 * a)).
Here: https://github.com/math-comp/real-closed/blob/master/theories/complex.v#L733-L760
I guess it should be renamed and backported.

2023-04-24 18:17 UTC, CohenCyril commented
Great... I think this would all be easier on top of real-closed (which explains the relation between a polynomial and its derivative, in terms of roots and variations).

2023-04-25 15:55 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root2 : 0 <= delta -> root p ((- b + sqrt delta) / (2 * a)).
weird that the monic version is derived from the general one, I would have thought the overway around would have been simpler

2023-04-27 15:56 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_canonical x :
Indeed, well actually `numFieldType` because we need `4 != 0`.

2023-04-27 15:56 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Let p := a *: 'X^2 + b*: 'X + c%:P.
Indeed, that seems better, did that.

2023-04-27 15:58 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root2 : 0 <= delta -> root p ((- b + sqrt delta) / (2 * a)).
The factoring lemma from real-closed is now integrated in the PR, thanks.

I would also have thought that doing min first would be more convenient but in fact it seems to rather be the other way round (my code was about 10% longer when proving monic version first end deriving generic version then).

2023-04-27 16:00 UTC, proux01 commented
Thanks for your reviews, here is a new version that take them into account. Indeed, the sign lemmas are probably easier to do in real-closed so I didn't add too many of them.

2023-04-28 12:20 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_canonical :
This is true for `F = fieldType`

2023-04-28 12:55 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_canonical :
How do you prove it? As I said above, at some point I need `4 != 0` and I don't know how to easily prove that for any `fieldType`.

2023-04-28 12:58 UTC, thery commented on mathcomp/algebra/ssrnum.v
> +Proof.
```coq
rewrite addrC [X in _ + X]addrC addrA -alg_polyC. 
by rewrite -[p]coefK poly_def degp !(big_ord1, big_ord_recr) /= expr0 expr1.
```

2023-04-28 14:48 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_canonical :
In fact it only requires `2 != 0` but that doesn't hold for any field (for instance, the field of boolean that you recently added :wink: ).

2023-04-28 16:23 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_monic_canonical :
`ringType` would require to assume the existence of `2^-1`, maybe a bit too much of a generalization?

2023-04-28 16:24 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Proof.
Nice alternative proof but what's the gain? (it's a tad longer than the one I provided)

Sidenote: for this kind of comments, don't hesitate to use github's "suggestion" button (the one marked +/- between "Preview" and "H B I")

2023-04-28 16:25 UTC, proux01 commented
Thanks for the generalization suggestion, I applied it.

2023-04-29 22:36 UTC, thery commented
Look good to me

2023-05-02 06:31 UTC, CohenCyril approved these changes
I approve of the contents. We can merge once the changelog is provided.

2023-05-02 06:32 UTC, CohenCyril commented on mathcomp/algebra/poly.v
> +Lemma deg2_poly_factored : p = a *: ('X - r1%:P) * ('X - r2%:P).
```suggestion
Lemma deg2_poly_factor : p = a *: ('X - r1%:P) * ('X - r2%:P).
```
maybe?

2023-05-02 06:33 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_lt_root1 x : x < r1 -> 0 < p.[x].
```suggestion
Lemma deg2_poly_gt0l x : x < r1 -> 0 < p.[x].
```
maybe?

2023-05-02 06:34 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_gt_root2 x : r2 < x -> 0 < p.[x].
```suggestion
Lemma deg2_poly_gt0r x : r2 < x -> 0 < p.[x].
```

2023-05-02 06:34 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root1_root2 x : r1 < x < r2 -> p.[x] < 0.
```suggestion
Lemma deg2_poly_lt0 x : r1 < x < r2 -> p.[x] < 0.
```

2023-05-02 06:34 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg2_poly_root1_root2 x : r1 < x < r2 -> p.[x] < 0.
+variants with `le0` and `ge0`

2023-05-02 06:38 UTC, CohenCyril requested changes
Overall the PR looks good. I have a few renaming suggestion and the following remarks:
- usually one will only use one of the normal, numclosed or realclosed version at a time, so I suggest putting the results in modules to be imported on demand. (And if several versions are used then the desambiguation is done by the prefix module name.) This is the case in `poly.v` for several classes of results. Not sure the `monic` results fall into this category though (so one might preserve the name prefix).
- you provide the sign results for concave polynomials, shouldn't we also add the results for the convex ones?

2023-05-09 14:30 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Lemma deg_le2_poly_ge0_ge0 : 0 <= a -> (forall x, 0 <= p.[x]) -> delta <= 0.
What about
```suggestion
Lemma deg_le2_poly_delta_ge0 : 0 <= a -> (forall x, 0 <= p.[x]) -> delta <= 0.
```

2023-05-11 09:34 UTC, proux01 commented
@CohenCyril CI green

2023-05-11 13:17 UTC, merged

2023-05-11 13:31 UTC, CohenCyril commented
> I added the label TODO: HB port to make sure someone ports this PR to
> the hierarchy-builder branch or I already opened an issue or PR (please cross reference).

@proux01 could you add the reference to the mathcomp 2 PR?

2023-05-11 13:32 UTC, CohenCyril commented
> I added the label TODO: HB port to make sure someone ports this PR to
> the hierarchy-builder branch or I already opened an issue or PR (please cross reference).

@proux01 could you add the reference to the mathcomp 2 PR?

2023-05-11 14:02 UTC, proux01 commented
Done (it's the other way round since this PR was targetting the master branch)