Adding perm-related lemmas for zipped sequences.
math-comp/math-comp pull request #1006
Opened 2023-05-04 19:27 UTC by jouvelot

##### Motivation for this change

I found these lemmas useful and suggest them to be added to `seq.v`, if deemed general enough.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers
- [ ] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)

##### Compatibility with MathComp 2.0

- [ ] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

2023-05-28 22:19 UTC, CohenCyril requested changes
Thank you for your contribution. Here is my review.

2023-05-28 22:19 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +  size s = size t -> unzip1 [seq nth (x, y) (zip s t) i | i <- l] = [seq nth x s i | i <- l].
I'm not sure about the name ... `unzip1_seq` sounds a bit too generic.
Maybe `unzip1_map_nth_zip` ?
(also please no line longer than 80 char)

2023-05-28 22:19 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Lemma unzip2_seq x y s t l :
same remark about the naming

2023-05-28 22:19 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Qed.
Hypotheses are too strong and the proof can be shortened.
```suggestion
Lemma perm_zip_sym (S T : eqType) (s1 s2 : seq S) (t1 t2 : seq T) : 
  perm_eq (zip s1 t1) (zip s2 t2) -> perm_eq (zip t1 s1) (zip t2 s2).
Proof.
have swap t s : zip t s = map (fun u => (u.2, u.1)) (zip s t).
  by elim: s t => [|x s +] [|y t]//= => ->.
by rewrite [zip t1 s1]swap [zip t2 s2]swap; apply: perm_map.
Qed.

```

2023-05-28 22:19 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Qed.
Hypotheses can be weakened (see wlog)
```suggestion
Lemma perm_zip1 (S T : eqType) (s1 s2 : seq S) (t1 t2 : seq T) : 
  size s1 = size t1 -> size s2 = size t2 -> 
  perm_eq (zip s1 t1) (zip s2 t2) -> perm_eq s1 s2.
Proof.
wlog [x y] : s1 s2 t1 t2 / (S * T)%type => [hwlog|].
  case: s2 t2 => [|x s2] [|y t2] //; last exact: hwlog.
  by case: s1 t1 => [|u s1] [|v t1]//= _ _ /perm_nilP.
move=> eq1 eq2 /(perm_iotaP (x, y))[ns nsP /(congr1 (@unzip1 _ _))].
rewrite unzip1_zip ?unzip1_seq -?eq1// => ->.
by apply/(perm_iotaP x); exists ns; rewrite // size_zip -eq2 minnn in nsP.
Qed.
```

2023-05-30 07:57 UTC, jouvelot commented
Thanks a lot, @CohenCyril. I'll look at this asap.

2023-06-02 11:18 UTC, jouvelot commented on mathcomp/ssreflect/seq.v
> +Qed.
Thanks @CohenCyril for the smarter proof and lemma statement. Something I don't understand in this proof though is how `x` and `y` can be defined so directly. Are all `eqType`s inhabited by default? Where is this visible in the library?

2023-06-03 08:30 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
This lemma still has two unused arguments: `x`and `y`. Also the use of `perm_zip1` with `_` suggests to use maximal implicits for the two types and put in front the arguments that cannot be inferred from the goal. In the case of  `perm_zip1` it is `t1` and `t2` and for  `perm_zip2` it is `s1` and `s2`.

2023-06-05 14:03 UTC, jouvelot commented on mathcomp/ssreflect/seq.v
> +
I'm not very familiar with maximal implicits, so I hope my corrections are the ones you had in mind.

2023-06-30 07:21 UTC, CohenCyril approved these changes
LGTM

2023-07-03 13:10 UTC, proux01 commented
Rebased, CI is as green as expected (because of https://github.com/math-comp/hierarchy-builder/pull/372 ), merging.

2023-07-03 13:10 UTC, merged