trying to fix #1170
math-comp/math-comp pull request #1179
Opened 2024-03-06 10:09 UTC by affeldt-aist

##### Motivation for this change

we're stuck (with @proux01)

what about keeping `order_morphism` (possibly renaming it)
and just add `monotonic` with the same definition as `order_morphism`
(changing `mono` -> `homo`) and a few lemmas (but no structure a priori)

FYI: @CohenCyril 

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers
- [ ] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)

##### Compatibility with MathComp 1.X

- [ ] I added the label `TODO: MC-1 port` to make sure someone ports this PR to
      the `mathcomp-1` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

2024-03-06 17:05 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
the whole point was to remove this

2024-03-06 17:25 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
Sure, but don't we need the monomorphisms when building the substructures of order structures? so that they retain the same order as the parent structure?

2024-03-06 18:10 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
Substructures are particular cases of subtypes, hence `val` is injective.
I don't understand what concern you are raising.

2024-03-07 08:41 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
Sorry, apparently, I mixed up `isOrderMorphism` with `isSubPOrder` and indeed my concern is void.

2024-03-07 12:01 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
Fixed, if CI is green we should be good

2024-03-07 14:43 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
> Sorry, apparently, I mixed up `isOrderMorphism` with `isSubPOrder` and indeed my concern is void.

Thanks for attracting my attention to this. Indeed this is too strong as well.

https://github.com/math-comp/math-comp/blob/6dea6e14b5e56147f68d9c687b43ea60cd61bf14/mathcomp/ssreflect/order.v#L5373

It should be instead 
```coq
HB.mixin Record isSubPOrder d (T : porderType d) (S : pred T) d' U
    of SubType T S U & POrder d' U := {
  val_le_subproof : {homo (val : U -> T) : x y / x <= y};
}.
```
What I was trying to say is: since `val` is already injective, it suffices to require `{homo (val : U -> T) : x y / x <= y}` for the theory to work properly. Of course, since the two definitions of `isSubPOrder` are equivalent, it is simply a question of ease of use (and could be fixed with a factory if we insists on not changing the interface) and not a matter of getting it right from a math point of view.

2024-03-07 14:48 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
While we are at it, I do not understand why the field is not simply called `le_val` and why `leEsub` and `ltEsub` are stated this way...

2024-03-07 16:21 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
> the two definitions of `isSubPOrder` are equivalent

I may be wrong but I don't thinks this is true: the partial order on the subtype could be the empty relation for instance (nothing is ordered), if the order on the supertype is non empty, homo would hold but not mono. It holds for *total* orders though, maybe some additional factory would then make sense.

> why leEsub and ltEsub are stated this way... in the master version

Historical reasons I guess, I did borrow that from some ancestor of signed.v in Analysis, but I agree that we should rather have `le_wval` with homo (though, it's already `omorph_le`) and `le_val` with mono.

2024-03-07 21:29 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
> > the two definitions of `isSubPOrder` are equivalent
> 
> I may be wrong but I don't thinks this is true: the partial order on the subtype could be the empty relation for instance (nothing is ordered), if the order on the supertype is non empty, homo would hold but not mono. It holds for _total_ orders though, maybe some additional factory would then make sense.

Oh you are right indeed... and I realize there are two distinct notions: subobjects in the category of posets (i.e. the definition with homo + inj) and subposets (the current notion, with mono) which happen to be the regular subjects. We probably want to have both, and they happen to coincide for total orders.

2024-03-08 12:01 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  omorph_inj : injective apply;
Indeed, what about the following course of action?
* open an issue pointing here to remember to add the "subobjects in the category of posets" structure
* merge this as it is since it's already an improvement and mostly fixes #1170

2024-03-08 13:04 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +  {homo f : x y / x <= y}.
I think that the qualified name of this constant should be `Order.monotonic`, and thus, this should not be declared in a theory module.

2024-03-14 15:24 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +  {homo f : x y / x <= y}.
Good point, fixed. I kept an abbreviation in POSyntax though because there is no other shorter notation and Order.monotonic is probably a bit long for common use.

2024-04-03 11:08 UTC, CohenCyril requested changes
Sorry for not noticing that before.

2024-04-04 16:06 UTC, merged

2024-04-05 08:05 UTC, proux01 commented
Thanks @CohenCyril and @affeldt-aist (the last commit should have been squashed but too late)

2024-04-05 12:55 UTC, affeldt-aist commented
Maybe I should have force-pushed but I was expecting a merge-squash as in MathComp-Analysis.
What about putting a work about this policy in the template for PRs?

2024-04-05 13:04 UTC, proux01 commented
Merge-squash wouldn't have been ideal here, there were two reasonnable commits, it would have been sad (although not dramatic) to squash them.