Rename char into char'
math-comp/math-comp pull request #1311
Opened 2024-12-10 21:16 UTC by Tragicus

##### Motivation for this change
https://github.com/math-comp/math-comp/pull/1308 is not backwards compatible, so I assume we need to rename the whole world first.

##### Minimal TODO list

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers
- [ ] tried to abide by the [contribution guide](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md)
- [ ] this PR contains an optimum number of meaningful commits

See [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) for details.

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs).

2024-12-16 18:22 UTC, CohenCyril commented on mathcomp/algebra/sesquilinear.v
> +                                2 \in [pchar F] -> forall u, '[u, u] = 0].
This renaming looks unnecessary...

2024-12-16 18:24 UTC, CohenCyril commented on mathcomp/field/finfield.v
> +(*                              pcharRp : p \in [pchar R] holds. This type has*)
This renaming looks unnecessary too. This is essentially the reason why we are duplicating `char` in the longer run ... :shrug:

2024-12-16 21:55 UTC, Tragicus commented on mathcomp/algebra/sesquilinear.v
> +                                2 \in [pchar F] -> forall u, '[u, u] = 0].
Changing definitions is not backwards compatible. If people try to prove it by hand, I will break their code when I change the definition of `char`.

2025-01-31 18:38 UTC, CohenCyril requested changes
There are still a few primes...

2025-01-31 18:38 UTC, CohenCyril commented on doc/changelog/03-renamed/1311-deprecate_char.md
> +	+ `char_lalg` -> `pchar_lalg`
There are still `'`s over there

2025-01-31 18:38 UTC, CohenCyril commented on doc/changelog/03-renamed/1311-deprecate_char.md
> +	+ `splitting_cyclic_primitive_root` -> `splitting_cyclic_primitive_root'`
And over there...

2025-01-31 18:38 UTC, CohenCyril commented on doc/changelog/03-renamed/1311-deprecate_char.md
> +	+ `FinDomainSplittingFieldType` -> `FinDomainSplittingFieldType'`
And here

2025-01-31 18:38 UTC, CohenCyril commented on doc/changelog/03-renamed/1311-deprecate_char.md
> +	+ `purely_inseparable_elementP` -> `purely_inseparable_elementP'`
And here

2025-02-05 11:40 UTC, Tragicus commented on doc/changelog/03-renamed/1311-deprecate_char.md
> +	+ `splitting_cyclic_primitive_root` -> `splitting_cyclic_primitive_root'`
Do I simply replace all of them with `_pchar`?

2025-03-28 09:24 UTC, affeldt-aist commented
This PR looks like it is almost done but is not in the milestone. It looks like it was forgotten, I am adding it.

2025-04-07 15:43 UTC, CohenCyril approved these changes

2025-04-07 15:49 UTC, merged