Adding are_allpairs predicate
math-comp/math-comp pull request #558
Opened 2020-09-01 11:20 UTC by CohenCyril

##### Motivation for this change

This predicate is useful in stating that a sequence of matrices all commute.
This is a part of #207.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-09-01 11:22 UTC, CohenCyril commented
@gares, @pi8027, @strub can one of you assign themselves?

2020-09-01 11:51 UTC, gares commented
It looks ok to me, but I'm not in love with the `are_` part of the name. Is it similar to something already existing?

2020-09-01 12:33 UTC, chdoc requested changes

2020-09-01 12:33 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +Definition are_allpairs {T : Type} (r : rel T) xs :=
I agree with @gares in not being happy with this name.

2020-09-01 12:33 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +move: (size xs) (iota 0 _) => k s; rewrite -map_cons !are_allpairs_map all_map.
The more natural generalization would probably be `_.+1` rather than `size xs`

2020-09-01 12:33 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +rewrite /are_allpairs/= ?rxx/= all_cat all_map; have [xxs/=|//] := boolP (all _ s).
This line has 83 characters, I suggest splitting it at the semicolon :grin:

2020-09-01 12:36 UTC, gares commented on mathcomp/ssreflect/seq.v
> +rewrite /are_allpairs/= ?rxx/= all_cat all_map; have [xxs/=|//] := boolP (all _ s).
@CohenCyril probably took my vscode configuration...

2020-09-01 12:37 UTC, chdoc commented
Also, is it useful to have `T : nonPropType` rather than `T : eqType` while requiring `r : rel T` to be a boolean relation? I mean, the proof of `are_allpairs_cons` is nifty, but I would have expected a simpler proof based in `are_allpairsP`.

2020-09-01 12:43 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +move: (size xs) (iota 0 _) => k s; rewrite -map_cons !are_allpairs_map all_map.
> Also, is it useful to have `T : nonPropType` rather than `T : eqType` while requiring `r : rel T` to be a boolean relation? I mean, the proof of `are_allpairs_cons` is nifty, but I would have expected a simpler proof based in `are_allpairsP`.

It may happen that a relation is decidable even on some non discrete types (e.g. a pair of an ordered type with a no discrete type), and I would like to preserve the full generality of the theorem on such occurences.

2020-09-01 12:43 UTC, CohenCyril commented
> Also, is it useful to have `T : nonPropType` rather than `T : eqType` while requiring `r : rel T` to be a boolean relation? I mean, the proof of `are_allpairs_cons` is nifty, but I would have expected a simpler proof based in `are_allpairsP`.

It may happen that a relation is decidable even on some non discrete types (e.g. a pair of an ordered type with a no discrete type), and I would like to preserve the full generality of the theorem on such occurences.

2020-09-01 12:45 UTC, CohenCyril commented
> It looks ok to me, but I'm not in love with the `are_` part of the name. Is it similar to something already existing?

I went back and forth a lot in the naming (the working name was the ugly `all11` (hence the 80 character overflow caused by sed)...
I am open to suggestions on the naming but I was pretty happy with this one being meaningful ("are all pairs satisfying r on s") and exposing the implementation using `allpairs` in the name itself..

2020-09-01 12:46 UTC, CohenCyril commented
Actually I would have gone for `is` except `are` is grammatically more accurate (since it is about a relation, not a predicate).

2020-09-01 13:06 UTC, chdoc commented
Well, the predicate states that "all pairs of `s` are _in_ the relation `r`" (using the usual mathematical speak of relations as sets/predicates). So how about `allpairs_in r s`? For this one even the partial application `allpairs_in r` seems reasonable to me. Unfortunately `in` is used differently elsewhere.

2020-09-01 13:58 UTC, chdoc commented
In any event, `are_allpairs r s` is a proposition not a question. So even `allpairs_are r s` ("all pairs _are_ r(-related)") seems preferable to me.

2020-09-01 14:07 UTC, gares commented
> So even `allpairs_are r s` ("all pairs _are_ r(-related)") seems preferable to me.

+1

To me the thing is messy because `allpairs` does not really build pairs but steals the name. If we had a `pairs` thing that builds the sequence of all pairs, we could use allpairs for your new concept, eg `allpairs r xs := all (fixup r) (pairs xs xs)`.

2020-09-01 14:27 UTC, chdoc commented
> To me the thing is messy because `allpairs` does not really build pairs but steals the name.

While the string "allpairs" appears in a considerable number of of lemmas, the definition `allpairs` seems to be virtually unused, because `allpairs` is (almost) always inlined. The only lemma about `allpairs` in `ssreflect` and `algebra` appears to be `allpairs_tupleP`. :thinking:

2020-09-01 21:28 UTC, CohenCyril commented
> > To me the thing is messy because `allpairs` does not really build pairs but steals the name.
> 
> While the string "allpairs" appears in a considerable number of of lemmas, the definition `allpairs` seems to be virtually unused, because `allpairs` is (almost) always inlined. The only lemma about `allpairs` in `ssreflect` and `algebra` appears to be `allpairs_tupleP`.

`allpairs` actually immediately unfolds to the idiom `[seq f x y | x <- s, y <- t x]` which gives its name to the lemmas, and it is a rather historic convention (the self-expanding definition is newer as far as I remember). Moreover it indeed does not form pairs but applies a function symbol `f` to them (and this function symbol can be dependent), sometimes it's a `pair`, sometimes a `sigT` and sometimes something else, so it makes it more flexible to let `f` variable.

I'm all in favor of `allpairs_are`anyway!

2020-09-02 07:51 UTC, gares commented
I saw that, allpairs maps a function overs all the pairs, which could be named, to me, map_allpairs. Anyway, I'm OK with the renaming proposed by @chdoc

2020-09-02 10:07 UTC, CohenCyril commented
I fixed the names and introduced the `mkseqP` idiom.

2020-09-02 11:33 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +Proof. by case: s => [|x s]; rewrite -1?[x :: s](mkseq_nth x); constructor. Qed.
Do you think that generating the `s = [::]` case, which reappears a as a subcase of the `s = mkseq f n` case preferable to requiring some `x0 : T`? If so, maybe replace `mkseq f n` with `mkseq f n.+1`, do avoid the case duplication?

2020-09-02 11:39 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Proof. by case: s => [|x s]; rewrite -1?[x :: s](mkseq_nth x); constructor. Qed.
Actually, no I'm not sure... and having `n` looks dangerous `(iota 0 n.+1)` might expand and the point of `mkseqP` was to abstract away these... Maybe I will switch to requiring `x0` here...

2020-09-02 11:47 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Proof. by case: s => [|x s]; rewrite -1?[x :: s](mkseq_nth x); constructor. Qed.
@chdoc looks better now I think

2020-09-02 11:48 UTC, CohenCyril commented
I have a new name suggestion: how about `allrel`?

2020-09-02 11:50 UTC, chdoc commented
> I have a new name suggestion: how about `allrel`?

I approve, in particular because it avoids the `_`, leading to nicer lemma names.

2020-09-02 12:10 UTC, chdoc approved these changes
LGTM (apart from the grammar error in the changelog :smirk: )

2020-09-02 12:10 UTC, chdoc commented on CHANGELOG_UNRELEASED.md
> +  asserts a relation `r` holds on all pairs of elements of `s`, and
which asserts _that_ / asserting _that_

2020-09-03 13:13 UTC, CohenCyril commented
@gare all good?

2020-09-03 13:52 UTC, merged