Expliciting relation between split and [lr]shift
math-comp/math-comp pull request #565
Opened 2020-09-01 13:07 UTC by CohenCyril

##### Motivation for this change

Adds lemma `split_ordP`, a variant of `splitP` which introduces
ordinal equalities between the index and `lshift`/`rshift`, rather
than equalities in `nat`, which in some proofs makes the reasoning
easier (cf `matrix.v`), especially together with the new lemmas
`eq_shift` and `eq_lshift`, `eq_rshift`, `eq_lrshift`, `eq_rlshift`,
`lrshiftP`, and `rlshiftP`.
Part of #207.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-09-01 13:08 UTC, CohenCyril commented
@amahboubi @LaurenceRideau @gares can one of you assign themself?

2020-09-01 18:20 UTC, thery requested changes

2020-09-01 18:20 UTC, thery commented on mathcomp/ssreflect/fintype.v
> +Lemma lrshiftP m n i j : (@lshift m n i <> @rshift m n j).
I would never have guessed the name of this theorem P?

2020-09-01 18:20 UTC, thery commented on mathcomp/ssreflect/fintype.v
> +Proof. by apply/negP => /eqP/rlshiftP. Qed.
why not simple apply/eqP/lrshiftP.

2020-09-01 18:20 UTC, thery commented on mathcomp/ssreflect/fintype.v
> +Proof. by apply/negP => /eqP/lrshiftP. Qed.
same as after

2020-09-01 18:20 UTC, thery commented on mathcomp/ssreflect/fintype.v
> +Lemma rlshiftP m n i j : (@rshift m n i <> @lshift m n j).
same as before

2020-09-02 10:05 UTC, CohenCyril commented on mathcomp/ssreflect/fintype.v
> +Lemma lrshiftP m n i j : (@lshift m n i <> @rshift m n j).
It is not used, so I removed it.

2020-09-02 10:05 UTC, CohenCyril commented on mathcomp/ssreflect/fintype.v
> +Proof. by apply/negP => /eqP/rlshiftP. Qed.
fixed

2020-09-02 10:05 UTC, CohenCyril commented on mathcomp/ssreflect/fintype.v
> +Proof. by apply/negP => /eqP/lrshiftP. Qed.
fixed

2020-09-02 10:05 UTC, CohenCyril commented on mathcomp/ssreflect/fintype.v
> +Lemma rlshiftP m n i j : (@rshift m n i <> @lshift m n j).
It is not used, so I removed it.

2020-09-02 10:06 UTC, CohenCyril commented
@thery I removed the theorems with unintuitive names. If one finds them useful, we can think of a better name and add them back later on.

2020-09-02 10:28 UTC, thery approved these changes

2020-09-03 13:10 UTC, CohenCyril commented
@gare, @thery merge?

2020-09-03 13:33 UTC, thery commented
@CohenCyril fine with me

2020-09-03 13:36 UTC, CohenCyril commented
> @CohenCyril fine with me

You are not the author, you can merge ;)

2020-09-03 13:38 UTC, merged