[do not merge] Polynomial evaluation and minimal poly of a diagonal matrix
math-comp/math-comp pull request #573
Opened 2020-09-02 22:51 UTC by CohenCyril

##### Motivation for this change

This PR states some essential properties about triangular and diagonal
matrices. In particular, it exhibits the characteristic polynomial of
triangular matrices, the minimal polynomial of diagonal matrices, and
explain how to evaluate a polynomial in a diagonal matrix.

- Part of #207.

##### Things done/to do

- [ ] Merge dependency first: #571.
- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-09-03 16:50 UTC, thery requested changes

2020-09-03 16:50 UTC, thery commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
this seems a typical proof by induction on triangular matrices.
Maybe ursubmx A = 0 and is_triang_mx (lrsubmx A)
could be usefull theorems to have in the library.
Same holds for diagonal matrices.

Also I have noticed that there is no doc for is_triang_mx and is_diag_mx in the header of matrix

2020-09-03 16:50 UTC, thery commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
in the file matrix, the style seems to have spaces before a //

2020-09-03 17:48 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
> Maybe ursubmx A = 0 and is_triang_mx (lrsubmx A)

Do you mean we should make it an idiom?

> Maybe ursubmx A = 0 and is_triang_mx (lrsubmx A)

I could extract them indeed.

> Same holds for diagonal matrices.

Since `is_diag_mx A -> is_trig_mx A` holds, it may not be necessary... do you think we should add all variants for diagonal matrices.

> Also I have noticed that there is no doc for is_triang_mx and is_diag_mx in the header of matrix

I thought I did it in #571... my bad...
￼

2020-09-03 17:49 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
I think the new style conventions depend on whether `//` is related to one `?id` or several... In this case, I believe you are right and we should put a spacE.

2020-09-03 17:56 UTC, thery commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
too complicated for my simple brain. You mean ?thm // and ?thm// will not have the same semantic?

2020-09-03 18:05 UTC, thery commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
Everyone that will do a proof by induction on the size of a triangular or a diagonal matrix will have to reprove this kind  of theorems. If you turn them into lemma, I think your proof of `det_trig` will become elementary.

2020-09-07 13:08 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
I tried to split & add many subresults. Can you tell me what you think?

2020-09-07 13:09 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
I mean that, even if the formal semantic is exactly the same, by convention: if `thm` alone spawned sublemmas then one may write `?thm//`, but if it is the combination of  `thm1` and `thm2` then we write `?thm1 ?thm2 //`.

2020-09-07 16:26 UTC, thery commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
very strange to me. Is someone will go to all the code to adopt this convention?

2020-09-07 16:29 UTC, thery commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
Initially I was thinking only about the structure lemmas : how is_diag and is_trig propagates to submatrix but maybe adding ad-hoc elimination theorems is ok too. I am not sure there are lot of them in the library.

2020-09-07 22:47 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
> Initially I was thinking only about the structure lemmas : how is_diag and is_trig propagates to submatrix

That's what I thought and did initially, but as I thought, it barely removed one line of proof. In order to become "elementary" I also needed to add the induction. There are a few ad-hoc theorem (e.g. `poly_ind`, `big_ind` and `last_ind`), but it is indeed not a frequent practice, and it is preferred to have "side loading lemmas" instead (e.g. `ubnP`), but in the case of matrices the main enemy is the conversion between `n.+1` and `1 + n`, which I do not know how to deal with as a "side" lemma.

2020-09-07 22:54 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
I don't know. Do you think I should backtrack on that?

2020-09-07 22:56 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
Some files already started adopting it. Maybe the PR can be accepted independently of this.
We can discuss this convention in a meeting, and then fix it uniformly (or not) depending on the outcome of the discussions.

2020-09-07 23:16 UTC, thery commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
So maybe we should not include the induction lemmas.

2020-09-07 23:26 UTC, thery commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
My fear is that this non-uniformity will remain but fine with me to accept the PR once we've decided about the inclusion of the induction theorems

2020-09-07 23:27 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
I was going to conclude the opposite :laughing:

2020-09-07 23:28 UTC, thery commented on mathcomp/algebra/matrix.v
> +have -> : ursubmx A = 0 by apply/matrixP => i j; rewrite !mxE Atrig//= ord1.
ok let's keep them

2020-09-07 23:29 UTC, thery approved these changes

2020-09-07 23:35 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +elim: n => [|n IHn] in A * => /is_trig_mxP Atrig; rewrite ?big_ord0 ?det_mx00//.
I opened issue #580 and I will put it in the list of topics.

2020-09-08 09:56 UTC, merged