Theory of stability of a subspace by an matrix representing an endomorphism.
math-comp/math-comp pull request #584
Opened 2020-09-08 19:50 UTC by CohenCyril

##### Motivation for this change

Added `stablemx` notation and a few lemmas about it.
Part of #207

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-10-09 09:54 UTC, ybertot requested changes
LGTM,
a small correction in English.

2020-10-09 09:54 UTC, ybertot commented on mathcomp/algebra/mxalgebra.v
> +(*  stablemx V f <=> the matrix f represents a endomorphism that preserves V *)
"a endomorphism" looks like an English mistake to me, "an endomorphism" would feel more idiomatic.

2020-10-09 09:54 UTC, ybertot commented on mathcomp/algebra/mxalgebra.v
> +Lemma stablemxC x : stablemx V x%:M.
Out of curiosity, where was the convention for the use of 'C' for the presence of x%:M described?

2020-10-12 09:41 UTC, gares commented on mathcomp/algebra/mxalgebra.v
> +(*  stablemx V f <=> the matrix f represents a endomorphism that preserves V *)
```suggestion
(*  stablemx V f <=> the matrix f represents an endomorphism that preserves V *)
```

2020-10-16 11:10 UTC, pi8027 commented on mathcomp/algebra/mxalgebra.v
> +Lemma stablemxC x : stablemx V x%:M.
The suffix `C` is also extensively used in lemmas about `x%:P` in `poly.v`. `C` stands for "constant" in both cases but it has not been documented in the contribution guide.

2020-10-21 13:56 UTC, CohenCyril commented on mathcomp/algebra/mxalgebra.v
> +(*  stablemx V f <=> the matrix f represents a endomorphism that preserves V *)
fixed

2020-10-21 13:56 UTC, CohenCyril commented
I fixed the typo

2020-10-22 09:49 UTC, ybertot approved these changes
LGTM

2020-10-25 12:40 UTC, CohenCyril commented
@gares any obstacle left to merging?

2020-10-26 14:16 UTC, merged