lemma used in mathcomp-analysis
math-comp/math-comp pull request #593
Opened 2020-09-12 08:04 UTC by affeldt-aist

##### Motivation for this change

Move a lemma from MathComp-Analysis to MathComp.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-09-14 16:40 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
```suggestion
Lemma max_real x y : x \is real -> y \is real -> max x y \is real.
Proof. by case: leP. Qed.

Lemma min_real x y : x \is real -> y \is real -> min x y \is real.
Proof. by case: leP. Qed.
```

2020-09-15 05:38 UTC, pi8027 requested changes
I guess `max_real` and `min_real` can be stated as follows as in `realD`.
```coq
Lemma max_real : {in real &, forall x y, max x y \is real}.
Lemma min_real : {in real &, forall x y, min x y \is real}.
```
Also I'm not sure if `bigmax_real` really requires `T : choiceType` (`eqType` might be enough).

2020-09-15 05:38 UTC, pi8027 commented on CHANGELOG_UNRELEASED.md
> +`
"Do not edit former entries."

2020-09-15 05:38 UTC, pi8027 commented on mathcomp/algebra/ssrnum.v
> +Proof. by move=> ?; elim/big_ind : _. Qed.
In this section, `R` is a `realDomainType`. They should be located in a section that assumes that `R` is a `numDomainType` (e.g., somewhere after `Lemma real_ltgt0P`).

2020-09-15 05:46 UTC, pi8027 commented on mathcomp/algebra/ssrnum.v
> +Proof. by move=> ?; elim/big_ind : _. Qed.
So `case: leP` should not be applicable to prove them. Use `real_leP` instead.

2020-09-15 09:41 UTC, pi8027 commented on mathcomp/algebra/ssrnum.v
> +  x \is real -> (forall t : T, t \in D -> f t \is real) ->
```suggestion
  x \is real -> {in D, forall t : T, f t \is real} ->
```
Should we also have `bigmin_real`?

2020-09-15 09:41 UTC, pi8027 commented on CHANGELOG_UNRELEASED.md
> +`
```suggestion
- in `ssrnum.v`, new lemmas `max_real`, `min_real`, `bigmax_real`

```

2020-09-15 11:46 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +  x \is real -> (forall t : T, t \in D -> f t \is real) ->
Yes we should.

2020-09-15 11:47 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +  x \is real -> (forall t : T, t \in D -> f t \is real) ->
There are two possible phrasing for `forall t : T, t \in D -> f t \is real` :
- either `{in D, forall t : T, f t \is real}`,
- or `{homo f : x / D >-> mem real}`

2020-09-15 12:45 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +
I suspect (and hope) this to be a one-liner in `T^d`

2020-09-15 12:46 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
I suspect (and hope) this to be a one-liner in `T^d`, e.g.
```suggestion
Proof. exact: (@bigmax_real [eqType of T^d]). Qed.
```

2020-09-15 15:20 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
The best practice is to have a conditional big with a `in` on the predicate, this allows the index type (renamed from `T` to `I`) to be any type (not necessarily an `eqType`). One can recover the desired behavior thanks to `big_seq_cond`.
```suggestion
Lemma bigmax_real I x0 (r : seq I) (P : pred I) (f : I -> R):
  x0 \is real -> {in P, forall t : I, f t \is real} ->
  \big[max/x0]_(t <- r | P t) f t \is real.
Proof.
by move=> x0r Pr; elim/big_rec : _ => // i x Pi xr; rewrite max_real ?Pr.
Qed.
```

2020-09-15 15:21 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
Same remark:
```suggestion
Lemma bigmin_real I x0 (r : seq I) (P : pred I) (f : I -> R):
  x0 \is real -> {in P, forall t : I, f t \is real} ->
  \big[min/x0]_(t <- r | P t) f t \is real.
Proof.
by move=> x0r Pr; elim/big_rec : _ => // i x Pi xr; rewrite min_real ?Pr.
Qed.
```

2020-09-15 15:22 UTC, CohenCyril commented
I think a similar result should appear in `order.v` for comparable elements.

2020-09-15 16:44 UTC, affeldt-aist commented
> I think a similar result should appear in `order.v` for comparable elements.

I guess that's not what you want, I'll investigate more tomorrow.

2020-09-15 17:24 UTC, CohenCyril commented
> > I think a similar result should appear in `order.v` for comparable elements.
> 
> I guess that's not what you want, I'll investigate more tomorrow.

not at all indeed ... It should look like:
```coq
{in P, forall x, x0 >=< x} -> {in P &, forall i j, f x >=< f y} ->
all (>=< \big[max/x0]_(i <- s | P i) f i) (x :: s).
```
With perhaps a particular case for `x` and for `s` when `I` is an `eqType`.

2020-09-17 10:36 UTC, pi8027 approved these changes
LGTM

2020-09-17 11:05 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +
Given the nice phrasing you found for `comparable_bigmin` these `all` variants seem useless to me. If needed, it's easy to prove on the spot without induction.
```suggestion
```

2020-09-17 11:06 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +Proof. by move=> ? ?; elim/big_ind : _ => // y z; exact: comparable_minl. Qed.
```suggestion
Lemma comparable_bigmax x0 I (P : pred I) (s : seq I) F x :
   x0 >=< x -> {in P, forall i, F i >=< x} ->
  \big[max/x0]_(i <- s | P i) F i >=< x.
Proof. by move=> ? ?; elim/big_ind : _ => // y z; exact: comparable_maxl. Qed.

Lemma comparable_bigmin x0 I (P : pred I) (s : seq I) F x :
   x0 >=< x -> {in P, forall i, f i >=< x} ->
  \big[min/x0]_(i <- s | P i) f i >=< x.
Proof. by move=> ? ?; elim/big_ind : _ => // y z; exact: comparable_minl. Qed.
```

2020-09-17 11:10 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
Naive question is this simply `exact: comparable_bigmax`, `exact: comparable_bigmin` now?

2020-09-17 11:11 UTC, CohenCyril commented
Subsidiary question: shouldn't we have a generic `comparable_big` which generalizes both `comparable_bigmax` and  `comparable_bigmin` under the assumption that the iterated operation preserves comparability?

2020-09-17 14:43 UTC, affeldt-aist commented on mathcomp/algebra/ssrnum.v
> +Qed.
Almost. Modulo `comparabler0` rewrite which make the script longer than a single line.

2020-09-17 14:48 UTC, affeldt-aist commented
> Subsidiary question: shouldn't we have a generic `comparable_big` which generalizes both `comparable_bigmax` and `comparable_bigmin` under the assumption that the iterated operation preserves comparability?

Indeed. But with the new `comparable_big`, the old `comparable_bigmax`
is not exactly `comparable_big comparable_maxl` because of the order of arguments of `comparable_maxl`.
(BTW, I changed the notation `>=< x` because it looked counter-intuitive to me.)

2020-09-26 20:54 UTC, CohenCyril commented
> > Subsidiary question: shouldn't we have a generic `comparable_big` which generalizes both `comparable_bigmax` and `comparable_bigmin` under the assumption that the iterated operation preserves comparability?
> 
> Indeed. But with the new `comparable_big`, the old `comparable_bigmax`
> is not exactly `comparable_big comparable_maxl` because of the order of arguments of `comparable_maxl`.

Then swap the arguments ;)

> (BTW, I changed the notation `>=< x` because it looked counter-intuitive to me.)

You are right!

2020-09-26 20:55 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
But now with `comparable_big` isn't it better?

2020-09-26 21:22 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +Hypothesis op_comparable : forall z, {in >=< z &, forall x y, op x y >=< z}.
This hypothesis is too weak...

2020-09-26 21:58 UTC, CohenCyril commented
BTW, making `comparable_minl` and `comparable_maxl` hints make `rewrite comparable_big//` simplify side conditions automatically if one rephrases them. I took the liberty to patch your PR, but I cannot seem to push in your branch, did you authorize pushs from maintainers?

2020-09-26 22:04 UTC, CohenCyril approved these changes
I patched this PR and I am ok with my own patch @pi8027 could you take a second look?

2020-09-26 22:06 UTC, CohenCyril commented
and ... rebased

2020-09-26 22:29 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Qed.
it is !

2020-09-26 22:30 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +Hypothesis op_comparable : forall z, {in >=< z &, forall x y, op x y >=< z}.
better now

2020-09-27 02:01 UTC, pi8027 commented on CHANGELOG_UNRELEASED.md
> +  `max_real`, `min_real`, and `bigmax_real`, `bigmin_real`.
```suggestion
  `max_real`, `min_real`, `bigmax_real`, and `bigmin_real`.
```

2020-09-27 02:06 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +Notation ">=< y" := ([pred x | comparable x y]) : order_scope.
The ordering of arguments of `comparable` has been changed here. This should be recorded in CHANGELOG in my opinion. Otherwise, this should be `comparable y x`.

BTW, I don't see why we define `>=< _` twice in here and L.1157 (but not from this PR).

2020-09-27 11:11 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +Notation ">=< y" := ([pred x | comparable x y]) : order_scope.
> The ordering of arguments of `comparable` has been changed here. This should be recorded in CHANGELOG in my opinion. Otherwise, this should be `comparable y x`.

Yes, it must be documented and the change is intentional.

> BTW, I don't see why we define `>=< _` twice in here and L.1157 (but not from this PR).

I think this is the unfortunate result of a copy paste from `<=` and `>=` and the fact the symbol  `>=<` is symmetric.

2020-09-28 05:18 UTC, pi8027 requested changes
The definition of `>=< y` in ssrnum should also be changed.

2020-10-09 11:40 UTC, CohenCyril commented
> The definition of `>=< y` in ssrnum should also be changed.

@affeldt-aist do you think you can do it?

2020-10-09 12:11 UTC, affeldt-aist commented
> > The definition of `>=< y` in ssrnum should also be changed.
> 
> @affeldt-aist do you think you can do it?

I'll try to by monday.

2020-10-12 11:25 UTC, pi8027 approved these changes
LGTM.

2020-10-22 02:21 UTC, pi8027 commented
@CohenCyril Can you confirm the last commit and merge this PR?

2020-10-22 10:02 UTC, merged