New lemmas about allpairs
math-comp/math-comp pull request #630
Opened 2020-11-04 13:35 UTC by CohenCyril

##### Motivation for this change

Fixes #497 en passant.

The former convention seemed to implicitly consit in dropping suffix
`l` when the `r` side does not exist as an equality (but rather as a
`=i` or now a `perm_eq`. If we want to change this convention, I can
open another PR after this one is merged, but it will involve even
more deprecation.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-11-08 22:01 UTC, pi8027 requested changes

2020-11-08 22:02 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +Lemma allpairs_rconsr f s y0 t :
```suggestion
Lemma perm_allpairs_rconsr f s y0 t :
```

2020-11-08 23:36 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Lemma allpairs_rconsr f s y0 t :
I'm anticipating on the next renaming, I wanted `perm_allpairs_rconsr` to be a temporary alias for `allpairs_rconsr`, I may have forgotten the alias though :laughing:

2020-11-09 00:08 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +Lemma allpairs_rconsr f s y0 t :
Ah, I see! I didn't read CHANGELOG entries. So please add the alias instead.

2020-11-09 00:46 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +  [seq f x y | x <- s, y <- t1 x] = [seq f x y | x <- s, y <- t2 x].
```suggestion
Lemma eq_allpairsr (f : forall x, T x -> R) s t1 t2 : (forall x, t1 x = t2 x) ->
  [seq f x y | x <- s, y <- t1 x] = [seq f x y | x <- s, y <- t2 x].
```

2020-11-09 01:01 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  `allpairs1l`, `allpairs1r`, `allpairs_cons`, `eq_allpairsl`,
```suggestion
  `allpairs1l`, `allpairs1r`, `allpairs_cons`, `eq_allpairsr`,
```

2020-11-09 20:16 UTC, pi8027 approved these changes
LGTM, but it would be nice if someone can take a second look.

2020-11-10 19:34 UTC, ybertot commented on CHANGELOG_UNRELEASED.md
> +  already deprecated in favor of `allpairs_rcons`, cf renamed
should be `allpairs_rconsr` here.

2020-11-11 00:21 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  already deprecated in favor of `allpairs_rcons`, cf renamed
```suggestion
  already deprecated in favor of `allpairs_rconsr`, cf renamed
```

2020-11-11 11:06 UTC, ybertot commented
I will merge this PR once it is squashed and rebased, if need be.

2020-11-11 11:49 UTC, CohenCyril commented
> I will merge this PR once it is squashed and rebased, if need be.

done.

2020-11-11 12:54 UTC, merged

2020-11-11 12:54 UTC, ybertot commented
Thanks