Generalize `allrel` to take two lists as arguments
math-comp/math-comp pull request #665
Opened 2020-11-20 07:54 UTC by pi8027

##### Motivation for this change

Closes #662.

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-11-20 08:20 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +End All1Rel.
I think most use-cases of `all1rel` require `r` to be symmetric. This is the case at least in `all_comm_mx`, `ahom_in`, and `Derivation`. But, if it is not the case in general, I would like to put the suffix `_sym` to the names of these lemmas.

2020-11-20 10:09 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
I prefer `all2rel` or `pairwise` than `all1rel`.
@gares, @chdoc, you participated in the first discussion on `allrel`, what do you say about this change and my suggestion?

2020-11-20 10:12 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +- by apply: ih2; have:= leT_total x y; rewrite ?allrel_consl ?xs2 ?xy //= => ->.
I'm a bit concerned that the proof looks longer...

2020-11-20 10:13 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Lemma allrel0s ys : allrel [::] ys. Proof. by []. Qed.
I had the impression that the convention here was `l` `r` rather than positional (as in `allpairs0l`)

2020-11-20 10:17 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +End All1Rel.
These lemma only make sense when the relation is symmetric anyway, otherwise it can all be obtained by `allrel_cons2` which would be the lemma combining `allrel_consr` and `allrel_consl`.

2020-11-20 10:18 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +- by apply: ih2; have:= leT_total x y; rewrite ?allrel_consl ?xs2 ?xy //= => ->.
```suggestion
rewrite allrel_cons2 => /and4P [xy' xs2 ys1 s1s2] /andP [hx xs1] /andP [hy ys2].
case: ifP => xy /=; rewrite (hx, hy) /=.
- by apply: ih1; rewrite ?allrel_consr ?ys1 //= xy xy' implybT.
- by apply: ih2; have:= leT_total x y; rewrite ?allrel_consl ?xs2 ?xy //= => ->.
```

2020-11-20 10:19 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +End All1Rel.
PS: and maybe that's what shortens the proof of `merge_stable_path` once more, as I tried to exhibit in [another comment](https://github.com/math-comp/math-comp/pull/665/files#r527591337)

2020-11-20 10:21 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
```suggestion

Lemma allrel_cons2 x y xs ys :
￼  allrel (x :: xs) (y :: ys) = [&& r x y, all (r x) ys, all (r^~ y) xs & allrel xs ys].
￼Proof. by rewrite /= all_predI/= -andbA. Qed. (* or something like that *)

```

2020-11-20 10:42 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +
I think we should rather provide a multi-rule rewriting lemma consists of `allrel_(cons|cat)(l|r)`, etc.

2020-11-20 10:43 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +(*                   in xs and ys.                                            *)
How about shortening the description to something along the lines of:
```suggestion
(* allrel r xs ys := all [pred x | all (r x) ys] xs                           *)
(*                == r x y holds whenever x is in xs and y is in ys           *)
```
I don't feel the need to use `proposition` here, as it it actually a boolean.

2020-11-20 10:43 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
I'm in favor of the new definition, I wasn't fond of the `all id ...` to begin with. As to to the naming, don't have much to say.

2020-11-20 10:51 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
On second thoughts, I prefer to reserve `pairwise` for
```coq
Fixpoint pairwise {T} (r : rel T) (xs : seq T) :=
  if xs is x :: xs then all (r x) xs && pairwise r xs else true.
```
That might come up in mathcomp 1.13 and that will be equivalent to `all2rel` under `reflexive r` and `symmetric r` only...

2020-11-20 10:54 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
We could have both, but the multirule rule may not lead to the same results modulo simpl :confused: so I'd rather let the user form them themselves at their own risk.

2020-11-20 10:55 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
What about `selfrel` ?

2020-11-20 11:05 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
Missing 
```coq
Lemma eq_allrel {T S : Type} (r r': T -> S -> bool) xs ys :
  r =2 r' -> allrel r xs ys = allrel r' xs ys.
Proof. (*...*) Qed.

Lemma eq_in_allrel {T S : Type} (P : {pred T}) (Q : {pred S}) (r r': T -> S -> bool) xs ys :
  all P xs -> all Q ys -> {in P & Q, r =2 r'} -> allrel r xs ys = allrel r' xs ys.
Proof. (*...*) Qed.
```

2020-11-21 07:18 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
@CohenCyril I thought your initial suggestion was to name the general version `all2rel` (https://github.com/math-comp/math-comp/issues/662#issuecomment-730807158). This one is fine with me. But, since I preferred to give a shorter name for a general version, I renamed the original `allrel` to `all1rel` ("1" stands for unary in the sense of that `all1rel` takes one list). Also, I'm not fond of `selfrel`...

2020-11-24 16:16 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
I prefer to keep `allrel` for the general version. But I was considering renaming `all1rel` to `all2rel` (expressing all 2 are related..., while I cannot read `all1rel` in english, besides interpreting `1` as the arity...).
However, it does not matter much to me, we can keep `all1rel`, at least for 1.12.

2020-11-24 16:17 UTC, CohenCyril requested changes
LGTM modulo changelog entry!

2020-11-25 03:21 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
> I prefer to keep `allrel` for the general version. But I was considering renaming `all1rel` to `all2rel` (expressing all 2 are related..., while I cannot read `all1rel` in english, besides interpreting `1` as the arity...).

Sure. Now I think it is fine to rename `all1rel` to `all2rel`.

2020-11-25 13:17 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  + lemmas `all1rel1`, `all1rel2`, and `all1rel_cons`
```suggestion
  + lemmas `all2rel1`, `all2rel2`, and `all2rel_cons`
```

2020-11-25 13:24 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
BTW, `pairwise` is also equivalent to `sorted` under transitivity. Reformulating some lemmas about `sorted` using `pairwise` may allow us to drop the transitivity assumption.

2020-11-25 13:25 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +(*   all1rel r xs := allrel r xs xs                                           *)
That would indeed be a nice thing to do... for mathcomp 1.13.0 :wink:

2020-11-25 13:28 UTC, CohenCyril approved these changes
Ready to merge, modulo rebase.

2020-11-25 17:59 UTC, merged