Fix deprecation notations in path.v
math-comp/math-comp pull request #670
Opened 2020-11-21 04:22 UTC by pi8027

##### Motivation for this change

Fix #668.

Since the first argument of `sorted_leq_nth` is maximally implicit, `@sorted_le_nth` does not simulate explicit application yet. We probably have to turn some of them into notations without deprecation for now.

##### Things done/to do

- ~[ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)~
- ~[ ] added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-11-23 11:35 UTC, chdoc requested changes
The sorted_(le|lt)_nth notations seem to work now.

2020-11-23 11:35 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +  (fun leT_tr leT_refl => @leq_index _ _ leT_tr leT_refl _) (only parsing).
This one still does not behave the same as `sorted_leq_index` wrt to apply:
```coq
Goal forall (s : seq nat) (srt_s : sorted leq s), {in s &, forall x y, index x s <= index y s -> x <= y}.
move => s srt_s. 
Fail apply: leq_index.
apply: sorted_leq_index. 
```
This is literally the first example I tried.

2020-11-23 12:13 UTC, pi8027 commented on mathcomp/ssreflect/path.v
> +  (fun leT_tr leT_refl => @leq_index _ _ leT_tr leT_refl _) (only parsing).
So we should remove the first two placeholders here as well.

2020-11-24 05:03 UTC, pi8027 commented
@chdoc @CohenCyril As in the description of this PR, some deprecation notations for explicit application such as `@sorted_le_nth` do not let us write the first two implicit arguments `T` and `leT`. IIUC, this is a limitation of the deprecation mechanism. I think we should rather turn them into notations without deprecation as in #640 for now. What do you think?

2020-11-24 08:08 UTC, CohenCyril commented
> @chdoc @CohenCyril As written in the description of this PR, some deprecation notations for explicit application such as `@sorted_le_nth` do not let us write the first two implicit arguments `T` and `leT`. IIUC, this is a limitation of the deprecation mechanism of MathComp. I think we should rather turn them into notations without deprecation as in #640 for now. What do you think?

How about setting an intermediate notation e.g. `sorted_leq_nth_subdef` with no maximal implicit?

2020-11-24 08:42 UTC, pi8027 commented
@CohenCyril If we pass such `sorted_leq_nth_subdef` as the second argument of `deprecate`, the deprecation message says `use sorted_leq_nth_subdef instead`.

2020-11-24 08:47 UTC, pi8027 commented
OK, I found a solution. This should be fine.

2020-11-24 09:23 UTC, chdoc approved these changes
Seems to work now.

2020-11-24 15:55 UTC, merged