Rework of PR #281: Archimedean structures on top of num/real domain/field/closedField
math-comp/math-comp pull request #682
Opened 2020-12-03 22:49 UTC by pi8027

##### Motivation for this change

This PR introduces several numeric domain structures with the Archimedean axiom. Currently, `classfun.v` is broken since it uses `Cint`, but importing `ssrint` adds the infix `^` notation which collides with that of `group_scope`.

Closes #281

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2020-12-04 12:37 UTC, pi8027 commented
> Currently, `classfun.v` is broken since it uses `Cint`, but importing `ssrint` adds the infix `^` notation which collides with that of `group_scope`.

It seems that group notations and ring notations are mixed almost everywhere in `classfun.v`. So there is no other solution than adding `%g` whenever required. If a scope declaration for arguments of coercion to `Funclass` works, this situation probably becomes better. But this does not work in the current implementation of Coq (see https://github.com/coq/coq/issues/5527#issuecomment-568242128):
```coq
Arguments fun_of_cfun [gT] [B] _ _%g.
```

2020-12-04 15:43 UTC, pi8027 commented
I guess `Qint` and `Qnat` should be deprecated and superseded by `Cint` and `Cnat` respectively. Right? @CohenCyril

2020-12-04 16:33 UTC, CohenCyril commented
> I guess `Qint` and `Qnat` should be deprecated and superseded by `Cint` and `Cnat` respectively. Right? @CohenCyril

Yes! And `Cint` and `Cnat` should both be renamed `Num.int` and `Num.nat`.

2020-12-04 16:34 UTC, CohenCyril commented
> > I guess `Qint` and `Qnat` should be deprecated and superseded by `Cint` and `Cnat` respectively. Right? @CohenCyril
> 
> Yes! And `Cint` and `Cnat` should both be renamed `Num.int` and `Num.nat`.

And they should be in the mixin, so as to make the computations for `ssrint` and `rat` faster!

2020-12-04 17:38 UTC, pi8027 commented
> > Yes! And `Cint` and `Cnat` should both be renamed `Num.int` and `Num.nat`.
> 
> And they should be in the mixin, so as to make the computations for `ssrint` and `rat` faster!

Make sense. Allowing the use of `Cint` without importing `ssrint` would also be nice to get a better fix for `classfun` and `inertia`. But reimplementing `Cint` theory in the absence of `ssrint` would require some more work.

2020-12-04 23:08 UTC, pi8027 commented
@CohenCyril Could you confirm this is what you mean?
```coq
Record mixin_of (R : numDomainType) := Mixin {
  trunc : R -> nat;
  is_nat : pred R;
  is_int : pred R;
  _ : forall x, 0 <= x -> (trunc x)%:R <= x < (trunc x).+1%:R;
  _ : forall x, is_nat x = ((trunc x)%:R == x);
  _ : forall x, is_int x = is_nat x || is_nat (- x);
}.
```

2020-12-05 01:00 UTC, pi8027 commented
> Yes roughly, except the truncation has no reason to be only for non negative numbers, I would prefer the function in the mixin to be more general, knowing that there could be a factory providing opaque `trunc`, `is_nat`, and `is_int` from a `nat` upper bound.

The problem is that we have to relocate the basic part of `ssrint` (`int` and `intmul` at least?) to `ssrnum` in order to generalize the truncation to the negative case.

> I had planned to wait for HB to make this kind of changes... I am a bit surprised you are willing to go through so much work while we intend to trivialize all of this...

Reworking an existing branch is easier to do now rather than later. Also, IMO actual difficulties appear in places other than the definitions of structures, as in the breakage of `classfun.v`.

2020-12-10 10:44 UTC, pi8027 commented
`Cnat`, `Cint`, `truncC`, and `floorC` have been renamed to `Num.nat`, `Num.int`, `Num.trunc`, and `floorR` respectively. I guess we have to relocate `ssrint.int` (or make the dependency from `ssrint` to `ssrnum` opposite) to rename `floorR` to `Num.floor` anyway.

2020-12-11 05:36 UTC, pi8027 commented
Almost done except that `floorR` is still not a part of the Archimedean mixin and defined in `ssrint`. I'm not sure what to do about this point.

2020-12-12 12:03 UTC, pi8027 commented
Here is a summary of possible solutions:
1. Keeping the dependency relation of libraries as is, placing `truncR`, `Rnat`, and `Rint` in `ssrnum`, and placing `floorR` in `ssrint` (the current situation):
   - Pros: This solution works.
   - Cons: `floorR` cannot be located in `ssrnum.Num` (we can declare another `Num` module in `ssrint` to work around this, but it seems troublesome). The `floorR` functions of `int` and `rat` cannot be as straightforward/efficient as we expect. The `archiNumDomainType` theory has to be separated into two parts (one in `ssrnum` and another in `ssrint`).
2. Keeping the dependency relation of libraries as is, but relocating `int` and `intmul` from `ssrint` to `ssrnum` or before to include `floorR` and related lemmas in `ssrnum`:
   I think this solution does not work, because statements and proofs of some lemmas about `floorR` require, e.g., canonical `ringType` and `orderType` instances of `int`. So we have to relocate a significant part of `ssrint` anyway.
3. Changing the dependency relation of libraries to make `ssrnum` requiring `ssrint`:
   This solution may work. But the canonical `numDomainType` of `int` has to be defined in `ssrnum` or later, and then some lemmas about `int` cannot be stated in `ssrint`, e.g., `abszE` which requires the norm function.
4. Adding another library that requires both `ssrnum` and `ssrint`, and relocating the Archimedean structures and related lemmas to it:
   I think this is the best solution among these, but requires at least two steps of transition.

2020-12-12 12:23 UTC, CohenCyril commented
Yet another solution: dispatching the contents of ssrint between ssralg and ssrnum.

2020-12-12 12:30 UTC, pi8027 commented
@CohenCyril That is what I meant in solution 3 IIUC.

2020-12-12 12:33 UTC, CohenCyril commented
> @CohenCyril That is what I meant in solution 3 IIUC.

Indeed. It was not clear to me whether you were suggesting to remove the file ssrint, which is what I suggest here.

2020-12-12 12:35 UTC, CohenCyril commented
Anyway, I like solution 4... it makes a lot of sense to me. How would you envision the transitiom though? Having files with new names required by files with old names?

2020-12-12 14:16 UTC, pi8027 commented
> Indeed. It was not clear to me whether you were suggesting to remove the file ssrint, which is what I suggest here.

I did not suggest removing `ssrint.v`. So they are actually different. But, anyway...

> Anyway, I like solution 4... it makes a lot of sense to me. How would you envision the transitiom though? Having files with new names required by files with old names?

In the first step, we try to relocate definitions and lemmas about the Archimedean structures as much as possible, to a new file, say `archimedean.v`. Since we have to deprecate `Znat` and related lemmas in `ssrint`, we cannot relocate some of them. So we declare them as `Local` ones in `ssrnum` or `ssrint`, provide deprecation aliases if needed, and also provide non-deprecated aliases in `archimedean.v`. I think this trick is also applicable to definitions of structures. In the second step, we remove deprecation aliases and relocate everything that depends on `archiNumDomainType` to `archimedean.v`.

2020-12-15 16:32 UTC, CohenCyril commented
The way I saw it was that `ssrnum.v` would be "fake file" `Require Export`ing `ssrnum_without_archimedean` (find a proper name e.g. just `num.v`) as well as `archimedean` so that there is no overlay to make for developments that used to depend in `ssrnum` but use archimedean structures.

2020-12-16 01:44 UTC, pi8027 commented
Currently, ssrnum.v defines both numeric and Archimedean structures, but some notations (e.g., archiNumDomainType) are deprecated there and re-exported from archimedean.v without deprecation. I also had to re-export the canonical declarations of closure properties of Num.nat and Num.int from rat.v and algC.v to fix the breakage (Cf the last commit).
Overlays are required to make hints working and they just insert a few simplifications. I will try to get rid of them if needed.

2020-12-16 09:47 UTC, gares commented on mathcomp/ssreflect/ssreflect.v
> +             note="Use the deprecated attribute instead.")]
yes!

2021-01-08 17:40 UTC, CohenCyril commented
I have opened #692 to control the impact of this PR.

2021-01-08 19:33 UTC, proux01 commented
@pi8027 the doc of floor reads

> Num.floor x == for x \in Num.real [...] else 0%Z

is there a lemma stating the else part?

2021-01-09 05:24 UTC, pi8027 commented
@proux01 That is missing and the `floor` function has to be redefined to prove it. I will do it before the next MathComp call. Thanks!

2021-01-18 19:19 UTC, CohenCyril commented on mathcomp/algebra/archimedean.v
> +Qed.
You could provide a non opaque function instead e.g.
```coq
Definition floorR x :=
   if x >= 0 then trunc x else let n := trunc (- x) in if x == n%:R then - n%:Z else - n.-1%N.
```
That way we can still compute (e.g. in Q) without having all the functions in the interface...

2021-01-22 05:08 UTC, pi8027 commented on mathcomp/algebra/archimedean.v
> +Qed.
@CohenCyril My plan is to extend the Archimedean mixin with the floor function in the next step (hopefully MathComp 1.14.0). So I would rather like to keep it opaque for now to prevent future breakages. For example, the floor function of `int` can simply be the identity function `fun n : int -> n` which is inconvertible with your general floor function.

2021-01-26 07:14 UTC, pi8027 commented
MathComp Analysis does not compile anymore:
```coq
- File "./theories/reals.v", line 486, characters 8-39:
- Error:
- In environment
- R : realType
- x : R
- The term "- x" has type "GRing.Zmodule.sort R"
- while it is expected to have type "Num.ArchiNumDomain.sort ?R".
```

It seems that there is no fix without adding an inheritance from `archiNumDomainType` to `realType`.

2021-01-27 09:54 UTC, pi8027 commented
@CohenCyril I think trying to be backward compatible is a bit painful in this case. Anyway, I agree that we should discuss this in a meeting. Meanwhile, I would like to revise the theory part of archimedean.v. (I have some questions and comments since I did not write everything by myself.)

2021-01-27 11:21 UTC, pi8027 commented on mathcomp/algebra/archimedean.v
> +Proof. by rewrite mulrNz eqr_oppLR -Rint_def !RintE opprK orbC. Qed.
We should rename these lemmas.

2021-01-27 11:21 UTC, pi8027 commented on mathcomp/algebra/archimedean.v
> +Lemma truncR_old x : trunc x = if 0 <= x then `|floor x|%N else 0%N.
This should be renamed.

2021-02-10 17:06 UTC, pi8027 commented
BTW, why CI disappeared from the checklist here?

2021-02-12 19:05 UTC, CohenCyril commented
> BTW, why CI disappeared from the checklist here?

no idea, that's very strange

2021-03-01 20:11 UTC, proux01 commented on mathcomp/algebra/archimedean.v
> +  x \is Rreal -> ~~ (x \is a Rint) = (ceil x == floor x + 1).
Indeed, here it is: https://github.com/proux01/math-comp/commit/881e7bb8b30d7d3baedb9bf2116bbc772be3a9b5

2021-03-01 20:12 UTC, proux01 commented on mathcomp/algebra/archimedean.v
> +    (floor x)%:~R <= x < (floor x + 1)%:~R else floor x == 0%N.
Thanks (although I don't see anything to add)

2021-03-01 20:14 UTC, proux01 commented on mathcomp/algebra/archimedean.v
> +Lemma Rint_def x : x \is a Rint = ((floor x)%:~R == x).
Maybe Rint_floor?

2021-03-08 12:34 UTC, CohenCyril commented
@pi8027 
> BTW, why CI disappeared from the checklist here?

This is now fixed (cf https://github.com/math-comp/math-comp/pull/706#issuecomment-792347741). In principle, if you rebased this PR for example, github would show the status of the CI. Although I believe with the ongoing stuff on HB it would not make sense to rebase it. Just so you know

2023-06-05 06:36 UTC, proux01 commented
@pi8027 @CohenCyril  now that 2.0 is out, I rebased this and CI is green. I'd like to merge by the end of the week if there is no more comments (I'll open an issue to remember the above points about `Rnat_sum_eq1` and `Rnat_prod_eq1`).

2023-06-05 16:03 UTC, proux01 commented
The remaining comments will be addressed in https://github.com/math-comp/math-comp/pull/1030 depending on this.

2023-06-07 15:59 UTC, proux01 commented
No more comments apparently so I'll merge on Friday.

2023-06-07 17:31 UTC, CohenCyril requested changes
Just a few remarks befor we merge.

2023-06-07 17:31 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +  is_int : pred R;
I advocate turning these into `_subdef`

2023-06-07 17:31 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Definition Rint : qualifier 1 R := [qualify a x : R | is_int x].
The `R` in `Rnat` and `Rint` does not respect any existing convention. It  should either be documented or renamed.
I am in favor of naming them `nat_num` and `int_num` inside this file, and then `nat` and `int` directly so that they can be used through `Num.nat` and  `Num.int` later on.

2023-06-07 17:31 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +  { R of NumDomain_isArchimedean R & RealField R }.
Maybe we can keep `archiFieldType` (at least as a notation) for this one, to maximize backward compat?

2023-06-08 12:09 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Definition Rint : qualifier 1 R := [qualify a x : R | is_int x].
Done, I thus renamed "Rnat" in lemma names to "nat" or "natr". This yields a few conflicts with "natr" already used for `%:R` which I solved using a few "nat_num". This is not perfect but I think it's acceptable.

Also note that we already had `Rpos`, `Rneg` and `Rreal` which should probably be deprecated/renamed `pos_num`, `neg_num` and `real_num` in a separate PR.

2023-06-08 12:10 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +  { R of NumDomain_isArchimedean R & RealField R }.
Ok, also changed `archiRealDomainType` to `archiDomainType` for the sake of uniformity.

2023-06-09 12:29 UTC, merged

2023-06-15 13:23 UTC, CohenCyril commented on mathcomp/algebra/ssrnum.v
> +Definition Rint : qualifier 1 R := [qualify a x : R | is_int x].
> Done, I thus renamed "Rnat" in lemma names to "nat" or "natr". This yields a few conflicts with "natr" already used for `%:R` which I solved using a few "nat_num". This is not perfect but I think it's acceptable.

I'm not sure having `natr` for lemmas about `nat_num` is desirable...


> Also note that we already had `Rpos`, `Rneg` and `Rreal` which should probably be deprecated/renamed `pos_num`, `neg_num` and `real_num` in a separate PR.

Sure we should also deal with `Rpos`, `Rneg` and `Rreal`

2025-04-09 16:18 UTC, pi8027 commented on mathcomp/algebra/ssrnum.v
> +Definition Rint : qualifier 1 R := [qualify a x : R | is_int x].
I opened an issue for this: #1330