Various lemmas
math-comp/math-comp pull request #738
Opened 2021-05-05 07:52 UTC by proux01

##### Motivation for this change

This is te content of my mathcomp_complements file in one of my developments (other than floor/cel lemmas already integrated in #682 ). So this is a bunch of unrelated lemmas. This may need some cherry picking as some lemmas may have no intereset. Naming might also be weak sometimes.

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2021-05-05 09:17 UTC, CohenCyril commented on mathcomp/algebra/intdiv.v
> +exact: leq_div2r.
```suggestion
by case: d => [[|d]|] _ [] m [] n//; rewrite /divz !mul1r; apply: leq_div2r.
```

2021-05-05 09:26 UTC, proux01 commented on mathcomp/algebra/intdiv.v
> +exact: leq_div2r.
Impressive contraction, I just added a `//` to avoid a warning.

2021-05-05 09:35 UTC, CohenCyril requested changes

2021-05-05 09:35 UTC, CohenCyril commented on mathcomp/algebra/intdiv.v
> +by case: (lcmn _ _).
```suggestion
have [->|m_neq0] := eqVneq m 0; first by rewrite lcm0z.
have [->|n_neq0] := eqVneq n 0; first by rewrite lcmz0.
by rewrite gt_eqF// [0 < _]lcmn_gt0 !absz_gt0 m_neq0 n_neq0.
```

2021-05-05 09:41 UTC, CohenCyril commented on mathcomp/algebra/intdiv.v
> +by case: (lcmn _ _).
@proux01 best practice is to use `have [] := view` instead of `case` for these. Also the choice of `view` is subtle, `eqP` is seldom used. We prefer `eqVneq`, `ifP`, `ifPn`, `ltgtP` and suff like that. Last resort is usually `boolP` or `altP reflection_lemma` (where `reflection_lemma` can be `eqP`).

2021-05-05 09:44 UTC, CohenCyril commented on mathcomp/algebra/intdiv.v
> +by case: (lcmn _ _).
Another best practice rather than assemble the hypotheses like you did is to either
- rewrite the goal like I did (backward reasonning)
- or make `have : intermediate_statement` (forward reasoning) and switch back to backward reasoning inside the subgoal,
Massaging hypothesis should be done with parsimony as it clutters the proof script slightly more than the above techniques.

2021-05-05 09:48 UTC, CohenCyril commented on mathcomp/algebra/intdiv.v
> +by case: d => [[|d]|] // _ [] m [] n //; rewrite /divz !mul1r; apply: leq_div2r.
```suggestion
by case: d => [[|d]|]// _ [] m [] n //; rewrite /divz !mul1r; apply: leq_div2r.
```
(save 1 char to respect the 80char per line limit)

2021-05-05 09:57 UTC, CohenCyril commented
@proux01 thanks for your contribution, it's likely all of this will be integrated. I will come back to your PR later to help with the tidying. Just some general remarks about mathcomp style meanwhile:
- do not use `{}` to focus, use the [mathcomp conventions](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md#indentation-in-proof-scripts)
- do not name hypothesis `Hsomething`, as expained [here](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md#naming-of-variables)

2021-05-05 12:56 UTC, gares commented on mathcomp/ssreflect/seq.v
> +rewrite (nth_map O); last by rewrite size_iota.
With no presumption of being correct, since I did not test it, these two lines look like they could be written as
```
rewrite (nth_map O) ?size_iota // (nth_map O) ?size_iota //.
```

2021-05-05 15:06 UTC, proux01 commented on mathcomp/ssreflect/seq.v
> +rewrite (nth_map O); last by rewrite size_iota.
Indeed, you are right.

2021-05-05 16:22 UTC, chdoc requested changes

2021-05-05 16:22 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +Qed.
```suggestion
Lemma drop_mask i (s : seq T) : 
  drop i s = mask (nseq i false ++ nseq (size s - i) true) s.
Proof. 
elim: i s => [|i IHi] s; last by case: s.
by rewrite drop0 /= mask_true // subn0.
Qed.

Lemma sorted_drop s i : sorted leT s -> sorted leT (drop i s).
Proof. rewrite drop_mask; exact: sorted_mask. Qed.
```

2021-05-05 16:22 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +Qed.
The `drop_mask` lemma should probably be moved elsewhere.

2021-05-05 16:45 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +Qed.
If you move this after the MakeSeq section, this can be proved by:
```
by move=> ?; rewrite -[in LHS](mkseq_nth x0 s) -map_take take_iota (minn_idPl _).
```

2021-05-05 16:47 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +Qed.
`elim: i s => [|i IHi] s; last by case: s.` -> `elim: i s => [|i IHi] []//`

2021-05-06 15:13 UTC, proux01 commented on mathcomp/ssreflect/path.v
> +Qed.
Almost
```
Lemma drop_mask i s :
  drop i s = mask (nseq i false ++ nseq (size s - i) true) s.
Proof. by elim: i s => [s|? ? []//]; rewrite drop0/= mask_true// subn0. Qed.
```

2021-05-06 15:14 UTC, proux01 commented on mathcomp/ssreflect/seq.v
> +Qed.
This was 81 chars so I just got the other way around (rewrite RHS instead of LHS).

2021-05-06 17:10 UTC, proux01 commented on mathcomp/ssreflect/path.v
> +Qed.
Unfortunately, this nice proof adds a useless hypothesis `transitive leT` :(

2021-05-11 16:25 UTC, CohenCyril commented
@proux01 I committed what we did together (and filled the proofs for the nth sorted lemmas)

2021-05-11 16:34 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +  i <= size s -> take i s = [seq nth x0 s j | j <- iota 0 i].
As discussed
```suggestion
Lemma map_nth_iota T (x0 : T) s i : i <= size s -> [seq nth x0 s j | j <- iota 0 i] = take i s.
```

2021-05-12 08:13 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +Qed.
If you're upset about the extra assumption, here is another possibility:
```coq
Lemma sorted_cat s1 s2 : sorted leT (s1 ++ s2) -> sorted leT s1 /\ sorted leT s2.
Proof.
by move: s1 s2 => [|x s1] [|y s2] //=; rewrite ?cats0 // cat_path /= => /and3P[].
Qed.

Lemma sorted_take n s : sorted leT s -> sorted leT (take n s).
Proof. by rewrite -[s in sorted _ s](cat_take_drop n) => /sorted_cat[]. Qed.

Lemma sorted_drop n s : sorted leT s -> sorted leT (drop n s).
Proof. by rewrite -[s in sorted _ s](cat_take_drop n) => /sorted_cat[]. Qed.
```

2021-05-13 15:31 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +Qed.
```suggestion
Proof. by rewrite -!size_filter filter_undup size_undup. Qed.
```

2021-05-13 15:31 UTC, pi8027 commented on mathcomp/ssreflect/seq.v
> +by rewrite s1_eq_s2.
```suggestion
move=> s1_eq_s2; rewrite -!size_filter !filter_undup.
apply/perm_size/perm_undup => x.
by rewrite !mem_filter; case: (boolP (a x)) => //= /s1_eq_s2.
```

2021-05-13 15:47 UTC, pi8027 commented on mathcomp/algebra/ssralg.v
> +Proof. exact: inj_eq fmorph_inj. Qed.
Lemmas in `ssralg` have to be exported from `GRing.Theory`. See #440.

2021-05-13 15:52 UTC, pi8027 commented
I will try to review order.v and path.v as well, but I think it will take some time.

2021-05-13 16:06 UTC, proux01 commented
@pi8027 please wait a bit, I'm still tidying them.

2021-05-14 07:43 UTC, proux01 commented
@pi8027 order.v and path.v should be cleaner now.

2021-05-14 09:04 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +Qed.
Nice!!!
Nitpicking:
- Please remove `%N` since it is inside `seq.v` there is no ambiguity.
- Also I would use `rewrite (@eq_in_filter _ _ pred0) ?filter_pred0// => i` instead of using`under` in this case.

2021-05-14 09:05 UTC, CohenCyril commented on mathcomp/ssreflect/order.v
> +move: (filter_all (>= x) s) => /all_nthP; apply; rewrite size_filter.
```suggestion
move: (filter_all (>= x) s) => /all_nthP; apply; rewrite size_filter.
```
I'd use `have /all_nthP := filter_all (>= x) s` instead of `move:` since `move:` is better suited to "meaningless" handling of the goal, while `have` marks key steps.

2021-05-14 09:08 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
Please add `take_mask` then :)

2021-05-14 09:08 UTC, CohenCyril commented on mathcomp/ssreflect/seq.v
> +
I personally prefer `dropEmask` and `takeEmask` though

2021-05-14 09:59 UTC, chdoc commented on mathcomp/ssreflect/seq.v
> +
I was about to say that `drop_mask` was badly chosen by me. I agree with the `E` variants.

2021-05-17 09:49 UTC, CohenCyril approved these changes
LGTM, ready to merge IMO

2021-05-18 06:41 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +by rewrite addn0 => ->; rewrite addnC -ltn_subLR ?subnn// -has_count has_pred1.
```suggestion
by rewrite addn0 => ->; rewrite -add1n leq_add2r -has_count has_pred1.
```

2021-05-18 06:41 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +by rewrite addnK.
```suggestion
by rewrite -(count_predC (> x)) addKn; apply: eq_count => y; rewrite /= leNgt.
```

2021-05-18 06:41 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +by rewrite addnK.
```suggestion
by rewrite -(count_predC (>= x)) addKn; apply: eq_count => y; rewrite /= ltNge.
```

2021-05-18 06:41 UTC, pi8027 commented on mathcomp/ssreflect/path.v
> +Proof. by move=> ? ?; rewrite !count_merge !count_cat; congr (_ + _). Qed.
```suggestion
Proof. by rewrite !count_merge !count_cat => -> ->. Qed.
```

2021-05-18 06:41 UTC, pi8027 commented on mathcomp/ssreflect/path.v
> +rewrite andbC /=; exact: leT_tr x'lex''.
```suggestion
by case: s => [//| x'' s xlex' /= /andP[x'lex'' ->]]; rewrite (leT_tr xlex').
```

2021-05-18 06:49 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +Section DualOrderTheory.
I think this should be a part of the `TotalTheory` module but it requires us to relocate `dual_orderType`. I can do this in a separate PR.

2021-05-18 07:45 UTC, proux01 commented on mathcomp/ssreflect/order.v
> +Section DualOrderTheory.
I agree, thanks!

2021-05-18 10:06 UTC, CohenCyril commented
@proux01 you need to rebase as well

2021-05-18 16:11 UTC, chdoc approved these changes
Apart from those two minor points, this LGTM.

2021-05-18 16:11 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +Proof. elim: s x i => [//| x s] IHs x' [//| i] /= /andP[-> ?]; exact: IHs. Qed.
This has nothing to do with sorting or ordering. If it is to be kept at all, it should be moved after `rcons_path` as:
```coq
Lemma path_take x p i : path x p -> path x (take i p).
Proof. by rewrite -{1}[p](cat_take_drop i) cat_path => /andP[->]. Qed.
```
@CohenCyril I'm never quite sure about the naming conventions for `path` lemmas (e.g., `cat_path` or `rcons_path`). So should this be `path_take` or `take_path?`.

2021-05-18 19:27 UTC, CohenCyril requested changes
@proux01 one last change following @chdoc remark and we are good to go

2021-05-18 19:27 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +Lemma path_take x p i : path x p -> path x (take i p).
Should be `take_path` (well spotted @chdoc).
Indeed unary predicates usually come as a suffix in mathcomp conventions, one can argue whether `path` is unary or binary, but the rest of the library seems to consider `x` as simply an accessory parameter and the only real parameter is `p`.

2021-05-18 19:27 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +Lemma sorted_cat s1 s2 : sorted leT (s1 ++ s2) -> sorted leT s1 * sorted leT s2.
should be `cat_sorted`

2021-05-18 19:27 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +Proof. by rewrite -[s in sorted _ s](cat_take_drop n) => /sorted_cat[]. Qed.
Should be `take_sorted` and `drop_sorted`

2021-05-18 20:21 UTC, chdoc commented on mathcomp/ssreflect/path.v
> +Lemma sorted_cat s1 s2 : sorted leT (s1 ++ s2) -> sorted leT s1 * sorted leT s2.
Shouldn't there actually also be an `E` somewhere (e.g. `cat_sortedE`) since the name refers to the shape of the premise rather than the conclusion?

2021-05-19 09:22 UTC, CohenCyril commented on mathcomp/ssreflect/path.v
> +Lemma sorted_cat s1 s2 : sorted leT (s1 ++ s2) -> sorted leT s1 * sorted leT s2.
@chdoc you are right about the fact this one is misnamed..., I was a bit too eager in my renaming suggestions.
It would not matter so much if there wasn't a possibly better candidate for being named `cat_sorted`, namely
```coq
Lemma cat_sorted x y s1 s2 (s1x := rcons s1 x) (ys2 := y :: s2) :
  sorted leT s1x ys2 = [&& x <= y, sorted leT s1x & sorted leT ys2].
```

However `E` lemma are usually "elimination equation" lemmas (taking a symbol to an equivalent definition), this is not the case here, so `car_sortedE` would also be misnamed

In this light, I suggest we'd rather name it `cat_sorted2` to signify both (2) sides of the `cat` are sorted, or that we keep `sorted_cat` even thought the name does not respect usual conventions.

2021-05-19 13:06 UTC, CohenCyril approved these changes

2021-05-19 13:14 UTC, CohenCyril commented
OK, let's merge as soon as CI passes \o/

2021-05-19 16:03 UTC, merged

2021-05-19 16:44 UTC, proux01 commented
Thanks all for your patience! I learned a lot.

2024-03-13 15:25 UTC, pi8027 commented on mathcomp/ssreflect/order.v
> +Section DualOrderTheory.
This should be addressed in #1166.