Fact 20210609
math-comp/math-comp pull request #752
Opened 2021-06-09 07:50 UTC by affeldt-aist

##### Motivation for this change

Lemmas about `fact` used to prove the convergence of the exponential series in MathComp-Analysis.
There is the `leq_fact` lemma in this PR and also the following `fact_split` lemma that I do not know
where to put. Any idea?

```
Local Open Scope nat_scope.

Lemma prod_rev n m :
  \prod_(0 <= k < n - m) (n - k) = \prod_(m.+1 <= k < n.+1) k.
Proof.
rewrite [in RHS]big_nat_rev /= -{1}(add0n m.+1) big_addn subSS.
by apply eq_bigr => i _; rewrite addnS subSS addnC subnDr.
Qed.

Lemma fact_split n m : m <= n -> n`! = \prod_(0 <= k < n - m) (n - k) * m`!.
Proof.
move=> ?; rewrite [in RHS]fact_prod mulnC prod_rev -big_cat [in RHS]/index_iota.
rewrite subn1 -iota_add subSS addnBCA // subnn addn0 [in LHS]fact_prod.
by rewrite [in RHS](_ : n = n.+1 - 1) // subn1.
Qed.

```

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2021-06-09 10:14 UTC, CohenCyril requested changes
As for the other two, I would put: 
```coq
Lemma fact_split n m : m <= n -> n`! = m`! * \prod_(m.+1 <= k < n.+1) k.
Proof. by move=> leq_mn; rewrite !fact_prod -big_cat_nat. Qed.
```
next to `fact_prod`.

And your `prod_rev` is too specific, both in the quantifications and in the sides of the equations.
It should be a bigop lemma instead, e.g.:
```coq
Lemma big_rev_mkord m n F : \big[op/idx]_(m <= k < n | P k) F k = \big[op/idx]_(k < n - m | P (n - k.+1)) F (n - k.+1).
Proof.
rewrite big_nat_rev (big_addn 0)/= big_mkord.
by apply: eq_bigr => i; rewrite -addSn addnC subnDr.
Qed.
```
I'm not yet sure about the name though...

2021-06-14 02:39 UTC, affeldt-aist commented on mathcomp/ssreflect/ssrnat.v
> +Lemma leq_fact n : n <= n`!.
Ok. I have added the `leq_fact` lemma (with `homo` instead of `mono`).

2021-06-14 02:40 UTC, affeldt-aist commented
> ```coq
> Lemma big_rev_mkord m n P F :
>  \big[op/idx]_(m <= k < n | P k) F k = \big[op/idx]_(k < n - m | P (n - k.+1)) F (n - k.+1).
> Proof.
> rewrite big_nat_rev (big_addn 0)/= big_mkord.
> by apply: eq_bigr => i; rewrite -addSn addnC subnDr.
> Qed.
> ```
> 
> I'm not yet sure about the name though...

By the look at `big_geq_mkord`, this looks like a reasonable name to me.

2021-07-07 14:22 UTC, CohenCyril commented on mathcomp/ssreflect/ssrnat.v
> +Lemma ltn_fact : {in [pred m | 0 < m], {homo factorial : m n / m < n}}.
I think for this I prefer to keep the expanded form, which should be convertible...
```suggestion
Lemma ltn_fact m n : 0 < m -> m < n -> m`! < n`!.
```

2021-07-07 14:23 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  and changed to use the `homo` notation
```suggestion
- `fact_smonotone` moved from `binomial.v` to `ssrnat.v` and renamed to `ltn_fact`.
```

2021-07-07 14:24 UTC, CohenCyril commented
> By the look at `big_geq_mkord`, this looks like a reasonable name to me.

@chdoc I remember seeing a comment about the name not being so reasonable to you, but I cannot find it anymore, did I imagine it?

2021-07-07 14:33 UTC, chdoc commented
I do not recall commenting on this name. :man_shrugging:

2021-07-07 14:36 UTC, CohenCyril commented
> I do not recall commenting on this name.

Maybe it was in a dream...

2021-07-07 14:39 UTC, CohenCyril commented
Ah I see, since I was not there, I imagined the worst:
https://github.com/math-comp/math-comp/wiki/Minutes-June-16-2021
> - PR 752:
>   - Cyril: to come back to it but this should be light
>   - Christian: questioning the naming of big_rev_mkord

Would you mind telling me your questioning and what answers you had?

2021-07-07 15:23 UTC, chdoc commented
From what I remember, I had simply missed that the order is in fact reversed, because my expectation was to find a lemma where the range has been shifted down (so that it begins with 0) without reversing the bigop. :man_shrugging:

2021-08-03 11:29 UTC, CohenCyril approved these changes
LGTM

2021-08-03 11:29 UTC, merged