Canonical additive, linear and rmorphism for fst and snd
math-comp/math-comp pull request #754
Opened 2021-06-13 10:33 UTC by hivert

There is zmod, ring, l-module and various Canonical structure on pairs but the projection fst and snd are missing algebraic structures. I'm adding those.

- [x ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)

2021-06-13 11:15 UTC, pi8027 requested changes
They should be re-exported from here. https://github.com/math-comp/math-comp/blob/8a5f000f9da3acc497a0393558f53f79cb20b30f/mathcomp/algebra/ssralg.v#L6165-L6196

2021-06-13 11:17 UTC, pi8027 commented
Also, this is a missing piece to support product rings in [algebra-tactics](https://github.com/math-comp/algebra-tactics). Thanks!

2021-06-13 11:39 UTC, hivert commented
> They should be re-exported from here.

Correct me if I'm wrong, but all those canonicals have to be re-exported because they were defined in a the Theory module. The new ones are defined outside...

2021-06-13 11:41 UTC, hivert commented
> Also, this is a missing piece to support product rings in [algebra-tactics](https://github.com/math-comp/algebra-tactics). Thanks!

I don't understand what you mean here (and know very little about tactic programming)...

2021-06-13 12:22 UTC, pi8027 commented
> > They should be re-exported from here.
> 
> Correct me if I'm wrong, but all those canonicals have to be re-exported because they were defined in a the Theory module. The new ones are defined outside...

Sorry, my bad. Indeed, instances for products are defined after the `GRing` module.

Could you investigate the breakage in separable.v? I guess you have to add some explicit patterns to specify subterms to rewrite.

> > Also, this is a missing piece to support product rings in [algebra-tactics](https://github.com/math-comp/algebra-tactics). Thanks!
> 
> I don't understand what you mean here (and know very little about tactic programming)...

Nevermind. I just wanted to show my support for this PR. But here are some details in the case you are interested in it: the algebra-tactics library provides ring and field tactics (as in Coq) for MathComp with a work-in-progress feature to support morphisms, e.g., it can prove `f ((x * y) ^+ 2) = f x ^+ 2 + f y ^+ 2 + f x * f y *+ 2` automatically, where `f` is a ring morphism to a `comRingType`. By relying on this feature and the canonical instances added by this PR, it should also be able to prove equations on product rings involving `fst`, `snd`, and `pair`.

2021-06-13 12:33 UTC, hivert commented
> Could you investigate the breakage in separable.v? I guess you have to add some explicit patterns to specify subterms to rewrite.

I'm doing it right now, but I must confess it seems more complicated than that I expected that replacing the failing

    rewrite -!rmorphM

by

      rewrite -[X in X + _]rmorphM -[X in _ + X]rmorphM.

should work but it doesn't. What is even strange it that 

       set mor := [rmorphism of map_poly at_t].
       rewrite -!(rmorphM mor).

work as expected ! However I expect that you won't accept such a crude fix.
The canonical is here and for some reason Coq fail to find the correct matching. I'm trying some more things, but It may be beyond my skills...


> Nevermind. I just wanted to show my support for this PR. 

Thanks !

> But here are some details in the case you are interested in it: the algebra-tactics library provides ring and field tactics (as in Coq) for MathComp with a work-in-progress feature to support morphisms, e.g., it can prove `f ((x * y) ^+ 2) = f x ^+ 2 + f y ^+ 2 + f x * f y *+ 2` automatically, where `f` is a ring morphism to a `comRingType`. By relying on this feature and the canonical instances added by this PR, it should also be able to prove equations on product rings involving `fst`, `snd`, and `pair`.

That is indeed very cool !

2021-06-13 13:32 UTC, hivert commented
I just pushed a reasonable fix. However I've no idea why it used to work and it is failing now. I don't know enough about Coq's pattern matching/canonical machinery to investigate further. If someone is able to understand and give me an explanation, please do !

2021-06-13 15:04 UTC, hivert commented
The failure seems to be unrelated... I don't know how to relaunch the test to be sure.

2021-06-14 02:35 UTC, pi8027 approved these changes
Except for a small remark, it looks good to me.

2021-06-14 02:35 UTC, pi8027 commented on mathcomp/field/separable.v
> +  by rewrite -![map_poly _ _ * _]rmorphM -rmorphD Dr /= map_polyC polyC_eqp1.
After all, I investigated this by myself. The source of the failure here was that it unifies `(u ^ at_t, v ^ at_t).1` with a morphism application and then triggers a canonical structure resolution. Without the morphism instances for `fst`, it unfolds `fst` to obtain `u ^ at_t` and finds the fact that `map_poly` is a morphism, but this behavior changes in presence of the morphism instances for `fst`. So `simpl` before `rewrite -!rmorphM` would be enough here:
```suggestion
  by rewrite /= -!rmorphM -rmorphD Dr /= map_polyC polyC_eqp1.
```

2021-06-14 15:58 UTC, hivert commented on mathcomp/field/separable.v
> +  by rewrite -![map_poly _ _ * _]rmorphM -rmorphD Dr /= map_polyC polyC_eqp1.
> After all, I investigated this by myself. The source of the failure here was that it unifies `(u ^ at_t, v ^ at_t).1` with a morphism application and then triggers a canonical structure resolution. Without the morphism instances for `fst`, it unfolds `fst` to obtain `u ^ at_t` and finds the fact that `map_poly` is a morphism, but this behavior changes in presence of the morphism instances for `fst`. So `simpl` before `rewrite -!rmorphM` would be enough here:

Thanks for the investigation and the explanation. I just applied your change (squashing the fix in a single commit) and (force) pushed. That should do the job.

2021-06-15 01:20 UTC, merged

2021-06-15 06:33 UTC, hivert commented
Good ! May I take the occasion to kindly ask the mathcomp project if they could put my name somewhere as an external contributor ? I've now probably more than 15 commit in the project, so that I think I deserve it ;-)

2021-06-15 07:21 UTC, pi8027 commented
We have a list of contributors for each release in its announcement e-mail. But, I personally think it makes a lot of sense to increase its visibility. I added it to the [topics](https://github.com/math-comp/math-comp/wiki/TopicsNextMeeting) for the next MathComp meeting (10 AM CEST tomorrow).