Generalizing ssralg.v telescopes.
math-comp/math-comp pull request #860
Opened 2022-03-07 17:55 UTC by jouvelot

##### Motivation for this change

I needed to add successive differences of natural numbers, `bigop`-style, and wrote a lemma that I thought could be made more general. I then discovered that something similar already exists in ssralg.v under the name of "telescope" (not the dependent-type version), although the current lemmas (and proofs) are specific to only two cases (`add` and `prod`). 

I suggest in this PR to generalize this notion of telescope so that these lemmas are all instances of a more general lemma, `telescope_op`. This one also handles my initial need for `nat`, and other applications can also be envisioned, e.g. the following (somewhat artificial) ones:
```
Lemma telescope_maxn_cste n m f a :
  n < m -> (forall n, f n = a) -> \max_(n <= k < m) f k = a.
```
or
```
Lemma telescope_maxn_dec n m f : 
  n < m -> {homo f : x y / x <= y} -> \max_(n <= k < m) maxn (f k) (f k.+1) = f m.
```

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2022-03-15 16:45 UTC, proux01 requested changes
Thanks for the pull request and sorry for the delayed answer.

2022-03-15 16:45 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +by apply/eqP; rewrite subr_eq0.
The new proof should be shorter
```suggestion
move=> lenm; apply: (telescope_op (fun i j => f j - f i) lenm (fun=> subrr _)).
by move=> k _ /=; rewrite addrCA addrAC subrr add0r.
```

2022-03-15 16:45 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +by move/eqP; rewrite ltn_eqF.
New proof should be shorter
```suggestion
move=> allu ltnm; rewrite (telescope_op (fun i j => f i / f j) (ltnW ltnm))//.
  by move=> /eqP; rewrite ltn_eqF.
move=> k nkm; rewrite /= mulrA divrK//; exact: allu.
```

2022-03-15 19:49 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
Thanks for taking the time looking at this PR and all the suggestions :) 

> * Nothing depends on ssralg here, so this could be put at the end of bigop.v.

I agree that the code should be dispatched somewhere else. I put it in one place, where its application was more meaningful, to make looking at it easier at the start of the review process. Should have I done the dispatch right from the start?

> * When adding definitions, like `shrink` and `empty`, they should be documented. But since they are used in only one lemma, maybe we just don't need specific definitions.

It seems to me that `shrink` could, if deemed sufficiently useful, actually be put in nat.v. (with a better name). This is a simplification I had to do in a project, on nats and also on ints.

> it seems the `shrink` hypothesis can be simplified to `∀ k, n < k < m → op (f n k) (f k k.+1) = f n k.+1` which leads to the following simplified proof

This is what I used at the start, but 1) this equality condition is only needed on a subset of the domain of `f`, which thus makes the subsequent lemmas stronger, and 2) it turned out to be needed, or at least useful, for the variant of the telescope I needed, which operated on ordinals. 

> (there might be a way to get rid of the Monoid hypothesis, but I didn't manage that)

I thought the Monoid was necessary for the `\big` construct.

2022-03-15 19:52 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +
> This should also be in bigop. 

I agree.

> It' also seems inverted to me.

I followed the pattern already used in ssralg.v, so that I didn't have to change one single line of the file there, just introduce the `telescope_op` abstraction.

2022-03-15 20:01 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
Should I dispatch the various proof elements in the files we discussed? Any suggestion about where exactly?

2022-03-16 09:57 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +End Telescope.
> I agree that the code should be dispatched somewhere else. I put it in one place, where its application was more meaningful, to make looking at it easier at the start of the review process. Should have I done the dispatch right from the start?

As you prefer, that's not needed for a first version of the pull request, just to discuss the change.
But that would have to be done at some point before merging.

> It seems to me that `shrink` could, if deemed sufficiently useful, actually be put in nat.v. (with a better name). This is a simplification I had to do in a project, on nats and also on ints.

Maybe. I currently think that just the `telescope_op` lemma doesn't expose such a need. But if you have other uses that would justify that, feel free to share them.

> This is what I used at the start, but 1) this equality condition is only needed on a subset of the domain of `f`, which thus makes the subsequent lemmas stronger, and 2) it turned out to be needed, or at least useful, for the variant of the telescope I needed, which operated on ordinals.

Then maybe add this lemma to the PR. Currently, it feels like proving a lemma under an hypothesis that is more complicated and stronger than needed, which is a shame.

BTW, I wonder whether the hypothesis about `n` and `m` in `telescope_op` shouldn't be `n < m` rather than `n <= m`, that would remove the need for the `n = m -> f n n = idx` hypothesis, and the equality case can easily be proved when needed (it doesn't depend on `telescope_op` itself).

> I thought the Monoid was necessary for the `\big` construct.

No (although it is very common), see `big_nat_recl` for instance (compared to `big_nat_recr`).

2022-03-16 10:00 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +End Telescope.
> Should I dispatch the various proof elements in the files we discussed? Any suggestion about where exactly?

I would say at the end of `bigop.v`, there for instance https://github.com/math-comp/math-comp/blob/master/mathcomp/ssreflect/bigop.v#L2056

2022-03-16 10:03 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +
I mean, `telescope_sumr` is in the order `\sum_(n ≤ k < m) (f k.+1 - f k) = f m - f n`, as well as `telescope_prodf`. Only `telescope_prodr` is in the order `\prod_(n ≤ k < m) (f k / f k.+1) = f n / f m`, but it holds a comment `(* Due to noncommutativity, fractions are inverted. *)`. So the order you suggested looks to me like "inverted" as per the existing code.

2022-03-16 21:32 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +
Oh, I see what you mean. I'm pushing a new version.

2022-03-16 21:35 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
- I'll try to clean up the lemma on ordinals I have to see whether that would more motivate the constraint in `shrink`. BTW, it seems to me that this added constraint in `shrink` makes `telescope_op` stronger, since the equality property only needs to be true on a subdomain of `shrink`.
- For `n <= m`or `n < m`, I don't know what's best. The lemma is more general with the inequality, and avoids users to prove the `=` case at the price of the `empty` definition. Both cases are present in `ssralg.v`. 
- I'll keep the functions in one location for now, and will move them in `bigop.v` once the code is finalized, then. Thanks for the suggestion.

2022-03-17 08:35 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +End Telescope.
> For n <= mor n < m, I don't know what's best.

I think we need both: `telescope_op : n < m -> ...` and `telescope_op_leq : n <= m -> (n = m -> f n n = idx) -> ...`

2022-03-17 08:38 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +Lemma telescope_addn n m f :
```suggestion
Lemma telescope_sumn n m f : 
```
to be consistent with the other names in ssralg.v

2022-03-17 09:39 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
> > For n <= mor n < m, I don't know what's best.
> 
> I think we need both: `telescope_op : n < m -> ...` and `telescope_op_leq : n <= m -> (n = m -> f n n = idx) -> ...`

Ok, let's try that. I'm pushing these two versions.

2022-03-17 12:25 UTC, proux01 commented on mathcomp/algebra/ssralg.v
> +End Telescope.
BTW, do we agree that
```forall k, n < k < m -> op (f n k) (f k k.+1) = f n k.+1```
is a weaker hypothesis than
```forall p q r, p < q < r -> (n <= p /\ r <= m) -> op (f p q) (f q r) = f p r```
(just taking p := n, q := k and r := k+1) thus making the lemma in my suggested change above stronger?

2022-03-17 12:41 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
Oh, sorry, I misread your previous question, and thought you were only getting rid of the `(n <= p /\ r <= m)` condition, which I needed for the ordinal-based lemma I had in a project:
```
Variable (k :nat) (f : 'I_k.+1 -> nat ) (af : {homo f : x y /~ x <= y}).

Definition ord_pred m (j : 'I_m) : 'I_m. 
have j1: j.-1 < m by rewrite (leq_ltn_trans _ (ltn_ord j)) // leq_pred.
exact: Ordinal j1.
Defined.

Lemma sum_diffs (l h : 'I_k.+1) : 
  l < h -> \sum_(s < k.+1 | l < s <= h) (f (ord_pred s) - f s) = f l - f h.
```
for which the bound condition was needed (and where my hunt for a more general started). So, yes, indeed, your suggestion is a weaker hypothesis, and probably enough; I'll reuse your shorter proof, and see whether I can make all my use cases work with this.

2022-03-17 15:03 UTC, CohenCyril requested changes
Nice contribution!
I have a few simplifications to make, let me push a commit.

2022-03-17 16:17 UTC, jouvelot commented on mathcomp/algebra/ssralg.v
> +End Telescope.
All the use cases mentioned in the motivation header of this PR can be nicely adapted to the current definitions, except for `sum_diffs`, which deals with ordinals. For this, I had to introduce a (stronger) version of `telescope_sumn`, as follows:
```
Lemma telescope_sumn' n m f : 
  n <= m -> {in [pred i | n <= i <= m] &, {homo f : x y / x <= y}} ->
  \sum_(n <= k < m) (f k.+1 - f k) = f m - f n.
```
Maybe it's possible to avoid the (meaningful, btw) restriction on the `homo` constraint, but I'm not sure. Since this provable using `telescope_op_leq`, maybe it's not worth mentioning it.

2022-03-17 16:55 UTC, proux01 commented
So, looks we are all set, I'll squash and merge by the end of the week if there is no further comment.

2022-03-19 22:25 UTC, merged