Add various lemmas about option
math-comp/math-comp pull request #874
Opened 2022-04-15 15:29 UTC by proux01

From the mathcomp_extra.v file of Analysis.

2022-04-18 02:30 UTC, affeldt-aist approved these changes

2022-04-19 14:22 UTC, proux01 commented
Thanks for the changelog, CI green

2022-04-19 23:46 UTC, affeldt-aist requested changes

2022-04-19 23:46 UTC, affeldt-aist commented on mathcomp/ssreflect/ssrbool.v
> +Definition pred_omap T (D : {pred T}) : pred (option T) :=
Shouldn't this be `pred_oapp`?

2022-04-20 07:47 UTC, proux01 commented on mathcomp/ssreflect/ssrbool.v
> +Definition pred_omap T (D : {pred T}) : pred (option T) :=
I find `pred_omap` more natural. It feels to me as an option map on predicates.
But I suck at monads, so you might still be right.

2022-04-21 00:24 UTC, affeldt-aist commented on mathcomp/ssreflect/ssrbool.v
> +Definition pred_omap T (D : {pred T}) : pred (option T) :=
I am not sure either but I have a doubt because of the mismatch between the name and the contents of the definition.

2022-04-21 13:54 UTC, proux01 commented on mathcomp/ssreflect/ssrbool.v
> +Definition pred_omap T (D : {pred T}) : pred (option T) :=
I agree, let's go for `pred_oapp` then.

2022-04-21 22:30 UTC, affeldt-aist approved these changes

2022-05-30 07:26 UTC, proux01 commented
@affeldt-aist more than one month without any comment, you can probably merge

2022-05-30 07:42 UTC, affeldt-aist commented
> @affeldt-aist more than one month without any comment, you can probably merge

Indeed. There is however a conflict in the changelog.

2022-05-30 10:22 UTC, merged