Add parsing notations for _ = _ :> int and the like
math-comp/math-comp pull request #919
Opened 2022-09-06 08:31 UTC by proux01

##### Motivation for this change

This way `2 = 1 :> int` is parsed as `2%Z = 1%Z` and not `2%R = 1%R`
(that is `Posz 2 = Posz 1` (matching the already existing printing only
rule for `_ = _ :> int`) and not `intmul GRIng.one 2 = GRing.one`).
This should enable to retrieve the parsing behavior of `_ = _ :> int`
before the introduction of the number notation in ring_scope.

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2022-09-06 09:05 UTC, amahboubi approved these changes

2022-09-06 09:05 UTC, amahboubi commented
(approval up to ci validation)

2022-09-08 14:01 UTC, proux01 commented
CI green, does this deserve a CHANGELOG entry?

2022-09-12 15:16 UTC, CohenCyril commented
> CI green, does this deserve a CHANGELOG entry?

It would be good, yes

2022-09-13 08:01 UTC, proux01 commented
done

2022-09-30 20:55 UTC, CohenCyril requested changes
Aside from that, let's merge

2022-09-30 20:55 UTC, CohenCyril commented on mathcomp/algebra/ssrint.v
> +  : ring_scope.
Nitpicking, but the conventions are `m` and `n`
```suggestion
Notation "m = n :> 'int'"  := (@eq int m%Z n%Z) (only parsing)  : ring_scope.
Notation "n = m :> 'int'"  := (Posz n = Posz m) (only printing)  : ring_scope.
Notation "m == n :> 'int'" := ((m%Z : int) == (n%Z : int)) (only parsing)
  : ring_scope.
Notation "n == m :> 'int'" := (Posz n == Posz m) (only printing) : ring_scope.
Notation "m != n :> 'int'" := ((m%Z : int) != (n%Z : int)) (only parsing)
  : ring_scope.
Notation "n != m :> 'int'" := (Posz n != Posz m) (only printing) : ring_scope.
Notation "m <> n :> 'int'" := (not (@eq int m%Z n%Z)) (only parsing)
  : ring_scope.
```

2022-10-02 11:37 UTC, CohenCyril approved these changes

2022-10-02 11:40 UTC, CohenCyril commented
Failure seems unrelated

2022-10-02 11:40 UTC, merged

2022-10-04 15:46 UTC, proux01 commented
> CI failure seems unrelated

Indeed, it's due to https://github.com/math-comp/multinomials/pull/63 not being merged yet.