Introduce vandermode matrix
math-comp/math-comp pull request #937
Opened 2022-10-21 02:27 UTC by yoshihiro503

##### Motivation for this change

Introduced Vandermonde Matrix and these determinants.

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2022-10-21 17:00 UTC, CohenCyril requested changes
Dear @yoshihiro503, thank you for your contribution, Vandermonde matrices are indeed an important object to have in mathcomp.

2022-10-23 16:29 UTC, proux01 commented
According to WP: https://en.wikipedia.org/wiki/Vandermonde_matrix the Vandermonde matrix seems to be the transpose, but they also say "Some authors define the Vandermonde matrix as the [transpose](https://en.wikipedia.org/wiki/Transpose) of the above matrix". I don't know which one we want here?

2022-10-24 00:33 UTC, CohenCyril commented
> According to WP: https://en.wikipedia.org/wiki/Vandermonde_matrix the Vandermonde matrix seems to be the transpose, but they also say "Some authors define the Vandermonde matrix as the [transpose](https://en.wikipedia.org/wiki/Transpose) of the above matrix". I don't know which one we want here?

We do want the transpose of the "normal one" (i.e. the one that is defined here) due to the specific conventions of the mathcomp library wrt that.

2022-10-24 08:05 UTC, proux01 commented
I don't get those specific conventions but I definitely trust you.

2022-10-24 16:15 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +End vandermonde.
> Was there a particular reason why the dimensions were not the same?

@affeldt-aist ?

2022-10-25 00:01 UTC, affeldt-aist commented on mathcomp/algebra/matrix.v
> +End vandermonde.
It looks like infotheo is using a non-square version of the Vandermonde matrix to define generalized Reed-Solomon codes but I do not have the reference material at hand right now.

2022-10-26 00:27 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +End vandermonde.
I restored the non-square definition

2022-10-28 17:31 UTC, CohenCyril requested changes
I took the liberty to alter a little bit the description, please integrate, fix anything I might have done wrong and rebase.

2022-10-28 17:31 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +(*                    progression of a[i].                                    *)
```suggestion
(* Vandermonde m a == the 'M[R]_(m, n) Vandermonde matrix, given a : 'rV_n    *)
(*                    /         1          ...           1              \     *)
(*                    |      (a 0 0)       ...      (a 0 (n - 1))       |     *)
(*                    |    (a 0 0 ^+ 2)    ...    (a 0 (n - 1) ^+ 2)    |     *)
(*                    |        ...                      ...             |     *)
(*                    \ (a 0 0 ^+ (m - 1)) ... (a 0 (n - 1) ^+ (m - 1)) /     *)
(*                 := \matrix_(i < m, j < n) a 0 j ^+ i.                      *)
```

2022-11-04 07:34 UTC, yoshihiro503 commented on mathcomp/algebra/matrix.v
> +(*                    progression of a[i].                                    *)
Thank you for the correction.  I have imported the commits and organized the history.

2022-11-07 14:21 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +(*                    progression of a[i].                                    *)
It seems that the documentation header went missing ...

2022-11-11 02:34 UTC, yoshihiro503 commented on mathcomp/algebra/matrix.v
> +(*                    progression of a[i].                                    *)
I had erased it by mistake. It is okay now.

2022-11-14 13:58 UTC, CohenCyril approved these changes
Great

2022-11-20 22:11 UTC, merged

2022-11-21 15:12 UTC, CohenCyril commented
Thank you @yoshihiro503