Mx
math-comp/math-comp pull request #949
Opened 2022-12-12 16:16 UTC by Tragicus

##### Motivation for this change

Generalizes a few operations on matrices (pointwise lifting of operations, moving diagonal matrices, scalar matrices and trace to the zmodType section).
Note that the last commit broke (and fixes again) diagonalizable_for_mxinpoly (mxpoly.v), some rewrite does not rewrite the same term depending on where diag_mx is defined.
Note that I did not edit CHANGELOG_UNRELEASED.md as I do not quite know how to extend it.

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2022-12-15 16:13 UTC, CohenCyril requested changes
Great! Thanks!
This looks good to me up to 2 things:
- line breaks at 80 char max (see my suggestions for breaking and indentation),
- changelog and header incomplete.
You can use https://github.com/math-comp/tools to generate a draft of the candidate addition to the file `CHANGELOG_UNRELEASED.md`
E.g. right now I get
```
### Added
- in file `mathcomp`,
  + new definition `map2_mx`.
  + new lemmas `map2_trmx`, `map2_const_mx`, `map2_row`, `map2_col`, 
    `map2_row'`, `map2_col'`, `map2_mxsub`, `map2_row_perm`, `map2_col_perm`, 
    `map2_xrow`, `map2_xcol`, `map2_castmx`, `map2_conform_mx`, `map2_mxvec`, 
    `map2_vec_mx`, `map2_row_mx`, `map2_col_mx`, `map2_block_mx`, 
    `map2_lsubmx`, `map2_rsubmx`, `map2_usubmx`, `map2_dsubmx`, `map2_ulsubmx`, 
    `map2_ursubmx`, `map2_dlsubmx`, `map2_drsubmx`, `eq_in_map2_mx`, 
    `eq_map2_mx`, `map2_mx_left_in`, `map2_mx_left`, `map2_mx_right_in`, 
    `map2_mx_right`, `map2_mxA`, `map2_1mx`, `map2_mx1`, `map2_mxC`, 
    `map2_0mx`, `map2_mx0`, `map2_mxDl`, `map2_mxDr`, `diag_mx_is_additive`, 
    and `mxtrace_is_additive`.

### Removed

- in file `mathcomp`, removed `telescope_sumr_eq`, `telescope_prodr_eq`, and 
    `telescope_prodf_eq`.

``` 
And it suggests to check what there is to say about:
```
### Maybe changed

- in file `mathcomp`, updated `oppmx`, `addmx`, `addmxA`, `addmxC`, `add0mx`, `diag_mx`, 
    `tr_diag_mx`, `diag_mx_row`, `diag_mxP`, `diag_mx_is_diag`, 
    `diag_mx_is_trig`, `scalar_mx`, `diag_const_mx`, `tr_scalar_mx`, 
    `scalar_mx_is_additive`, `is_scalar_mx`, `is_scalar_mxP`, 
    `scalar_mx_is_scalar`, `mx0_is_scalar`, `scalar_mx_is_diag`, 
    `is_scalar_mx_is_diag`, `scalar_mx_is_trig`, `is_scalar_mx_is_trig`, 
    `mx11_scalar`, `scalar_mx_block`, `mxtrace`, `mxtrace_tr`, `mxtrace0`, 
    `mxtraceD`, `mxtrace_diag`, `mxtrace_scalar`, `trace_mx11`, 
    `mxtrace_block`, `diag_mx_is_linear`, `trmx1`, `scale_scalar_mx`, 
    `scalemx1`, `scalar_mx_sum_delta`, `mx1_sum_delta`, `row1`, `col1`, 
    `perm_mx`, `mxtrace_is_scalar`, `mxtraceZ`, `mxtrace1`, `matrix_nonzero1`, 
    and `scalar_mx_is_multiplicative`.
```

2022-12-19 15:54 UTC, Tragicus commented
Except for the new line that I do not find, it should be ok.

2022-12-20 16:05 UTC, ybertot commented on mathcomp/algebra/matrix.v
> +(*                     ABf congruent to A with Af i j = f (A i j) for all i   *)
I don't understand the explanation here.  Shouldn't it be
"the matrix ABf congruent with A with ABf i j = f (A i j) (B i j) for all i and j"?

2022-12-20 16:19 UTC, Tragicus commented on mathcomp/algebra/matrix.v
> +(*                     ABf congruent to A with Af i j = f (A i j) for all i   *)
Many thanks.

2022-12-21 09:12 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +Lemma map2_mx_right (f : R -> R -> R) : f =1 (fun _ x => x) ->
```suggestion
Lemma map2_mx_right (f : R -> R -> R) : f =2 (fun _ x => x) ->
```
otherwise it will be rather difficult to instanciate without funext.
Alternatively
```suggestion
Lemma map2_mx_right (f : R -> R -> R) : (forall x y, f x y = y) ->
```

2022-12-21 09:12 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +Lemma map2_mx_left (f : R -> R -> R) : f =1 (fun x _ => x) ->
```suggestion
Lemma map2_mx_left (f : R -> R -> R) : f =2 (fun x _ => x) ->
```
otherwise it will be rather difficult to instanciate without funext.
Alternatively
```suggestion
Lemma map2_mx_left (f : R -> R -> R) : (forall x y, f x y = x) ->
```

2022-12-21 12:10 UTC, Tragicus commented on mathcomp/algebra/matrix.v
> +Lemma map2_mx_left (f : R -> R -> R) : f =1 (fun x _ => x) ->
Right, thanks.

2022-12-21 13:47 UTC, CohenCyril commented on mathcomp/algebra/matrix.v
> +
```suggestion
```

2022-12-23 11:24 UTC, CohenCyril approved these changes

2022-12-23 11:26 UTC, merged