Backport math-comp/analysis#779
math-comp/math-comp pull request #952
Opened 2022-12-16 16:10 UTC by proux01

##### Motivation for this change

Backport math-comp/analysis#779

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2023-01-03 17:57 UTC, CohenCyril reviewed
I approve, but I'm also a contributor to the backported code, so I'd rather have someone else approve formally. @thery @affeldt-aist @ybertot any volunteer?

2023-01-04 08:56 UTC, proux01 commented
> PS: BTW @proux01 maybe there should be a Co-Authored-By crediting me, @affeldt-aist and IshiguroYoshihiro and Takafumi Saikawa ?

Indeed, done

2023-01-10 09:01 UTC, affeldt-aist commented on mathcomp/ssreflect/bigop.v
> +Lemma sub_big_idem (I : eqType) s s' P (F : I -> R) :
Shouldn't this be `idem_sub_big` following the pattern of `uniq_sub_big`?

2023-01-10 09:01 UTC, affeldt-aist commented on mathcomp/ssreflect/bigop.v
> +Lemma sub_big_idem_cond (I : eqType) s s' P P' (F : I -> R) :
Same comment as for `idem_sub_big`.

2023-01-10 09:09 UTC, affeldt-aist approved these changes
I browsed the changes and only had one comment.
I found that some lemmas have very short names such as `subset_big`.
When looking for this lemma for example I could have been tempted to
include the substring `le` in my `Search` command. Would it make sense
to have a bit longer but more informative name? Maybe it is for usage to say.

2023-01-10 16:13 UTC, ybertot commented on mathcomp/ssreflect/bigop.v
> +by rewrite big_mask big_tnth// -!(big_ACE opA opC) sub_big// => j /andP[].
First instance of // here is useless and can be removed.

2023-01-10 16:18 UTC, proux01 commented
> I found that some lemmas have very short names such as `subset_big`. When looking for this lemma for example I could have been tempted to include the substring `le` in my `Search` command. Would it make sense to have a bit longer but more informative name?

@affeldt-aist  I tend to agree, I added `le_` in bigop lemmas were it was absent. Does that feel better?

2023-01-11 08:55 UTC, proux01 commented
> There are two pending comments, but they are probably the same. The UI does not let me see them.

Here, I can click on "show resolved" on the right to expand them.

2023-01-11 09:15 UTC, ybertot requested changes
I think the name big_ACE is badly chosen.  This is a technical lemma, mainly useful as an intermediate step to reason about bigmin and bigmax, it lifts a plain big operation to the same big operation on an option type, with the benefit that the new big operation will benefit from all the existing material on communtative monoid laws.

Because it is a technical lemma, the name does not need to be short.  On the other hand, because it introduces quite a lot of complexity, it should be more informative.

suggestion `big_AC_lift_option`

2023-01-11 10:16 UTC, ybertot commented
After discussion in a developer meeting, we chose to support a name with suffix "_mk_monoid", so the best name seems to be `big_AC_mk_monoid`

2023-01-11 10:44 UTC, proux01 commented
Thanks, done

2023-01-18 09:41 UTC, affeldt-aist commented
> > I found that some lemmas have very short names such as `subset_big`. When looking for this lemma for example I could have been tempted to include the substring `le` in my `Search` command. Would it make sense to have a bit longer but more informative name?
> 
> @affeldt-aist I tend to agree, I added `le_` in bigop lemmas were it was absent. Does that feel better?

Yes, I think it is better this way.

2023-01-18 14:36 UTC, thery commented
I have a naive question : why big is not defined in such a way that 
`big[+%/0]_(i <-  [::x1, .... xn]) f i` is not simply ` (f x1 + (f x2 + .. f xn)) `  and 
`big[+%/0]_(i <-  [::]) f i` is `0.` 
It would make all this trick about big_max not necessary.

2023-01-18 16:23 UTC, CohenCyril commented
> I have a naive question : why big is not defined in such a way that
> `big[+%/0]_(i <- [::x1, .... xn]) f i` is simply `(f x1 + (f x2 + .. f xn))` and
> `big[+%/0]_(i <- [::]) f i` is `0.`
> It would make all this trick about `big_max` not necessary.

It might change lots of other behaviours in the non semi-group case ... We should try though.

2023-01-18 16:36 UTC, proux01 commented
> It might change lots of other behaviours in the non semi-group case ... We should try though.

Even in the non monoid case? But since many lemmas address the monoid case, this might be bearable, I agree we should try.

Isn't this point relatively orthogonal to that PR though?

2023-01-18 16:45 UTC, CohenCyril commented
@thery we tested briefely with @affeldt-aist, the new definition would invalidate `big_rec2` and `big_rec3` which have many occurrences, we did not push the experiment forward. AFAIU this changes too much the behaviour of bigop for non-monoids.
CC @ggonthier

2023-01-18 18:07 UTC, thery commented
The only drawback I see is that we don ´t have `big[+%/0]_(i <-  x :: l)  f i = f x + big[+%/0]_(i <- l) f i` anymore.

2023-01-18 19:12 UTC, proux01 commented
It also seem we would loose `big_rec`.

2023-01-18 19:16 UTC, ybertot approved these changes
LGTM

2023-01-18 19:18 UTC, thery commented
So it was a bad idea, I have learned something today

2023-01-20 12:59 UTC, merged