Building finite fields using polynomial and irreducible polynomial.
math-comp/math-comp pull request #959
Opened 2023-01-19 15:56 UTC by thery

…en size, finite field and discrete logarithm

##### Motivation for this change

THis is an attempt to finally have the classic construction of finite field using polynomial and irreducible polynomial.
I have tried to merge 3 contributions : https://github.com/math-comp/math-comp/pull/879, https://github.com/math-comp/math-comp/pull/210 and [divpoly](https://github.com/thery/mathcomp-extra/blob/master/divpoly.v).

This is not perfect and could be improved. So any feedback is welcome

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2023-01-19 17:40 UTC, Alizter commented on mathcomp/algebra/qpoly.v
> +(* This file minic the zmod file for polynomial                               *)
```suggestion
(* This file mimics the zmod file for polynomials                             *)
```

2023-01-19 19:04 UTC, thery commented on mathcomp/algebra/qpoly.v
> +(* This file minic the zmod file for polynomial                               *)
thanks

2023-01-20 14:48 UTC, CohenCyril requested changes
That's great that you pulled together all of this.
I left a few comments about typos and namings mostly.

Also could you please edit your commit log message so as to credit the other contributors:
```
Co-Authored-By: Cyril Cohen <cyril.cohen@inria.fr>
Co-Authored-By: josh <joshcohen98@gmail.com>
```
Thanks

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(* This file minic the zmod file for polynomial                               *)
```suggestion
(* This file mimic the zmod file for polynomial                               *)
```
I'm not sure this is the most explicative introducing sentence for the file.
Maybe something like this would be more appropriate:
```suggestion
(* This file defines the algebras R[X]/<p> and their theory.                  *)
```

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(* x.-lagrange_ i == the ith lagrange polynomial wrt the sampling points x    *)
I think in mathcomp we capitalize proper names, maybe we should?

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*                   if p is monic ans of size> 1 it is p otherwise 'X        *)
```suggestion
(*                   if p is monic and of size > 1 it is p otherwise 'X       *)
```
Should we expose this?

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*     in_qpoly p == turn the polynomial p into an element of {qpoly p} by    *)
```suggestion
(*     in_qpoly q == turn the polynomial q into an element of {qpoly p} by    *)
```

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*    primitive_poly p == p is a primitive polynome                           *)
```suggestion
(*    primitive_poly p == p is a primitive polynomial                         *)
```

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*     qlog sp_gt2' q == is the discrete log of q where q is an element of    *)
Why `qlog` and not `qlogp` (to mimic `logn` and `logp`) ?

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +  (at level 0, n at level 2, format "'{poly_' n  R }").
There should be a `Reserved Notation` at te beginning of the file.

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +Local Notation npolyR := (@npoly_of (Phant R) n).
We could write
```suggestion
Local Notation "'{poly_' n R }" := (@npoly_of (Phant R) n).
```
for the sake of uniformity.

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +Notation "{qpoly  p }" := (qpoly p).
There should be a `Reserved Notation` and probably some quotes as in the `'{poly_' n }` notation.

2023-01-20 14:48 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
Wouldn't it look nicer as : `{poly R %/ p}` to denote the quotient?
(and why not where `R` could be omitted but printed back)

2023-01-20 16:29 UTC, thery commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
I have always problem with this.
As it is now R is a ringType, my worry is to ugly prettyprint when the ringType has been inferred from p.

2023-01-20 22:18 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
ok... then how about printing `{poly %/ q}` ?

2023-01-20 22:23 UTC, CohenCyril commented
BTW we should also add the structures of algebra, field algebra, field extension and normal field extension when it makes sense. (So as to provide the missing ingredients for the zulip topic [Explicit construction of F256](https://coq.zulipchat.com/#narrow/stream/237664-math-comp-users/topic/Explicit.20construction.20of.20F256))

2023-01-21 00:10 UTC, thery commented
For algebra I can do it, for the other structure I am less familiar (but I will have a look) but this indicates that we should split qpoly.v  moving the construction of qfpoly to field.

2023-01-21 00:17 UTC, thery commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
ok but `{qfpoly mi}`  stays like this or we go  `{poly %f/  mi}`?

2023-01-21 16:09 UTC, thery commented
@CohenCyril ok I am stuck in the galois thing. I still have to understand what I actually need to prove.

2023-01-21 21:22 UTC, thery commented
@CohenCyril  ok I have done somehing but  with no control as  I don't understand the comments about the problems with finType and canonical structure in `finfield.v`.

2023-01-22 16:58 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(* x.-lagrange_ i == the ith lagrange polynomial wrt the sampling points x    *)
Sure... but [`Gauss`](https://github.com/math-comp/math-comp/blob/547ab317ade3ae546dc4e49c698108d58891c373/mathcomp/ssreflect/div.v#L909) and [`Lagrange`](https://github.com/math-comp/math-comp/blob/4d5fe7603d53482012734011c70f508e6726959a/mathcomp/fingroup/fingroup.v#L1932)

I think in the long run none of these theorems should carry a proper name (since there is a huge overloading, Gauss, Lagrange, Cauchy, etc theorems are legion), but that there should be an annotation/docstring/attribute to give the common name of the theorem.

Hence, matters little until this is done, and let's keep it as such for now...

2023-01-22 17:11 UTC, CohenCyril commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
Or `{poly %/ q given mi}`, `{poly %/ q using mi}` or something else that would be less "symbolic" ?

2023-01-22 17:11 UTC, CohenCyril commented
> @CohenCyril ok I have done somehing but with no control as I don't understand the comments about the problems with finType and canonical structure in `finfield.v`.

I'll take a look

2023-01-23 13:36 UTC, thery commented
@CohenCyril what I don't understand is why once you are a finite field you don't have automatically all the good properties and you still have to do something.

2023-01-23 16:04 UTC, thery commented on mathcomp/algebra/qpoly.v
> +(*      {qpoly p} == defined as {poly_(size (mk_poly p)).-1 R} on which       *)
done

2023-01-27 09:48 UTC, thery commented
We have checked the compatibility with #879 and  [Verified-FEC](https://github.com/thery/Verified-FEC/tree/qpoly).

2023-04-19 09:28 UTC, affeldt-aist commented
This PR was briefly mentioned during today's meeting (https://github.com/math-comp/math-comp/wiki/Minutes-April-19-2023) where participants wondered about the status.

2023-04-19 12:52 UTC, thery commented
should work on it next week. Two things to do 
1) Add some theorems in order to avoid unfolding 
2) Understand what it means port to HB

2023-04-19 13:56 UTC, proux01 commented
The HB port can be done afterwards (I had a quick look and I'm not too worried, basically replacing the `Canonical`s by `HB.instance`s should do the job, I could provide help if needed).

2023-05-02 11:39 UTC, thery commented
@CohenCyril   ok it reshapes a bit the PR, should be ok now

2023-05-31 07:08 UTC, proux01 commented
@thery I rebased instead of merge to get a simpler history and I updated the CI which is now green.

@CohenCyril you requested some change so I guess this is on your side now

2023-05-31 09:42 UTC, thery commented
@proux01 thanks Pierre!

2023-05-31 13:34 UTC, CohenCyril approved these changes
Looks good to me, I just have a few minor remarks

2023-05-31 13:34 UTC, CohenCyril commented on mathcomp/field/qfpoly.v
> +Definition qfpoly_const (R : idomainType) (h : {poly R})
```suggestion
Definition qfpolyC (R : idomainType) (h : {poly R})
```

2023-05-31 14:11 UTC, pi8027 commented on mathcomp/algebra/poly.v
> +Lemma poly_natmul n : n%:R%:P = n%:R :> {poly R}.
It seems to me that this lemma is just an instance of `rmorph_nat` after `Canonical polyC_rmorphism`.

2023-05-31 22:47 UTC, thery commented on mathcomp/algebra/poly.v
> +Lemma poly_natmul n : n%:R%:P = n%:R :> {poly R}.
@pi8027 well spotted! Is it ok to keep since `rmorph_nat` is not found by `Search`

2023-05-31 23:28 UTC, thery commented
@CohenCyril  Thanks!

2023-07-02 17:36 UTC, CohenCyril commented on mathcomp/algebra/polydiv.v
> +Lemma modp_id p q : (p %% q) %% q = p %% q.
Sorry, I realize my comment never was posted... 
Could you just add a deprecation for this?
```suggestion
#[deprecated(since="mathcomp 2.1.0", note="Use modp_id instead.")]
Notation modp_mod := modp_id.
```

2023-07-02 17:38 UTC, CohenCyril commented on mathcomp/algebra/polydiv.v
>  Qed.
Sorry, I realize my comment never was posted... 
Could you just add a deprecation for this?
```suggestion
Lemma modp_id p q : (p %% q) %% q = p %% q.
Proof.
by have [->|qn0] := eqVneq q 0; rewrite ?modp0 // modp_small ?ltn_modp.
Qed.

#[deprecated(since="mathcomp 2.1.0", note="Use modp_id instead.")]
Notation modp_mod := modp_id.
```

2023-07-04 09:26 UTC, merged