Generalize ler_sqrt
math-comp/math-comp pull request #986
Opened 2023-03-28 15:38 UTC by proux01

##### Motivation for this change

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md` (do not edit former entries)
- ~[ ] added corresponding documentation in the headers~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and make sure there is a milestone.

2023-03-28 16:43 UTC, proux01 commented
No, there seems to be no Nix derivation for apery. Should I add one based on the OPAM package (is it up to date ?).

2023-04-05 11:36 UTC, proux01 commented
@pi8027 I added algebra-tactics and apery in the CI and apery is indeed the only thing to break. Would you welcome an overlay that make apery depend on MC >= 1.17 or do you need backward compatibility?

2023-04-18 06:54 UTC, proux01 commented
@pi8027 gentle ping, what would you like for Apery?

2023-08-22 11:51 UTC, affeldt-aist requested changes
Maybe add the generalization of `ler_psqrt` to the changelog?

2023-08-28 08:21 UTC, proux01 commented
@affeldt-aist thanks, I'm waiting for https://github.com/math-comp/algebra-tactics/pull/71 so that Apery can be ported to MC2 to complete this.

2023-09-20 09:34 UTC, proux01 commented
Thanks!

2023-10-18 09:14 UTC, affeldt-aist commented
This just needs to be rebased.

2023-11-21 14:04 UTC, proux01 commented on mathcomp/algebra/ssrnum.v
> +Lemma ler_psqrt : {in @nneg R &, {mono sqrt : a b / a <= b}}.
@CohenCyril according to https://github.com/math-comp/math-comp/blob/c2bc27b04699320c18f4f46e7e39a77b02be2e20/mathcomp/algebra/ssrnum.v#L69-L72 the correct prefix here would be `p` and should have been `sp` before?

2023-11-24 17:03 UTC, proux01 commented
Let's finally merge that one.

2023-11-24 17:04 UTC, merged